### ISSUE TITLE
ETA for v2.0.0?

### ISSUE THREAD

**Issue by pat-s** [r-lib/cli#117]
Some packages are waiting for cli v2.0.0 to hit CRAN :)

**Comment by gaborcsardi** [comment]
Any day now....

**Comment by gaborcsardi** [comment]
Ideally, asciicast would be published first, but CRAN has been sitting on it for 10 days now, so I might just go ahead with cli.

**Comment by pat-s** [comment]
Good news! 🎉 Thanks for all the effort!

**Comment by gaborcsardi** [comment]
On CRAN now, please let us know if you find any glitches. Thanks!
