### ISSUE TITLE
Don't set background colour for code

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#123]
Since it looks bad whenever the lines have padding, e.g. https://cli.r-lib.org/reference/cli_code.html#examples

**Comment by gaborcsardi** [comment]
Yeah, it does not look good there, but it looks good on the screen:

<img width="760" alt="Screen Shot 2019-12-09 at 9 44 16 PM" src="https://user-images.githubusercontent.com/660288/70475733-16b80d00-1acd-11ea-8cd0-b07362321b6a.png">
<img width="676" alt="Screen Shot 2019-12-09 at 9 44 08 PM" src="https://user-images.githubusercontent.com/660288/70475735-16b80d00-1acd-11ea-8a5f-31ce8db70e9d.png">

But I agree that it needs improvements. Some ideas:
- we can turn off the syntax highlight for now.
- have a different color scheme for syntax highlighting. In RStudio, we could get the color scheme from the RStudio theme.
- have a different them in pkgdown.

**Comment by hadley** [comment]
It doesn't look good in RStudio either:

<img width="980" alt="Screenshot 2019-12-09 at 4 23 30 PM" src="https://user-images.githubusercontent.com/4196/70478271-4c92cc80-1aa0-11ea-8cc3-36e85c1a1d01.png">

**Comment by gaborcsardi** [comment]
OK, I'll turn off the bg in RStudio and get the colors from the theme. I'll also get some colors for pkgdown, based on the light bg.

**Comment by gaborcsardi** [comment]
I can get the RStudio themes from the source: https://github.com/rstudio/rstudio/tree/master/src/cpp/tests/testthat/themes/acecss

**Comment by gaborcsardi** [comment]
Partially fixed here: https://github.com/r-lib/prettycode/commit/1685923d2be91e33086f5cafd8b974ab8138c64c

I'll also remove the background in a sec....
