### ISSUE TITLE
Use pluralization to create error messages

### ISSUE THREAD

**Issue by krlmlr** [r-lib/cli#142]
I love the new pluralization feature. To use it in tibble, I need to access this functionality for throwing or constructing error messages. Would you consider exporting `glue_cmd()`, perhaps with a different name and with an option to turn off markup?

**Comment by gaborcsardi** [comment]
We want to support formatting and styling error messages in cli, but it needs a bit more thinking.

**Comment by gaborcsardi** [comment]
This is probably solved by the `format_error()` and `cli_abort()` functions.
