### ISSUE TITLE
[Feature Proposal] Convert R function to cli program

### ISSUE THREAD

**Issue by cfhammill** [r-lib/cli#143]
It would be nice if there was an easy way to augment a single R function responsible for a CLI with a parser so that it can be run from the command line.

This may be out of scope for this package - although I think this feature is too small to be its own package.  Would you consider adding a function -> CLI program conversion function (possibly powered by [argparser](https://cran.r-project.org/web/packages/argparser/index.html)), alternatively this function could be a better fit for that package. My thought is something that converts

```r
main <- function(input = "/home/me/", out = "/home/you/"){
  # awesome cli code
}
```

into

```r
library(argparser)

args <- 
  arg_parser("main") %>%
  add_argument("input", default = "/home/me/") %>%
  add_argument("output", default = "/home/you/") %>%
  parse_args()

main(input = args$input, output = args$output)
```

The naive version would be easy enough to write. Because of R's amazing reflection capabilities we can inspect on the formals of the function to get argument names and defaults.  Although constraining and or coercing the input types might be subtle. 

Let me know if this is of interest, and I can open a WIP PR.

**Comment by gaborcsardi** [comment]
I agree it would be nice to have better ways to write R scripts, but I don't think this is in the scope of cli. FWIW cli has some example scripts here: https://github.com/r-lib/cli/tree/master/inst/examples/apps

**Comment by cfhammill** [comment]
I figured, thanks @gaborcsardi
