### ISSUE TITLE
cli_verbatim does not respect margins

### ISSUE THREAD

**Issue by tzakharko** [r-lib/cli#146]
Not sure if this is a bug, but if a container has defined margins/padding, only the first verbatim line respects those. An example:

    cli_div(theme = list(.block = list("margin-left" = 4)))
    cli_verbatim("hello", "hello")  

outputs

        hello
    hello

In contrast, 

    cli_div(theme = list(.block = list("margin-left" = 4)))
    cli_verbatim("hello")
    cli_verbatim("hello")

outputs 

        hello
        hello

which seems counter-intuitive behavior to me. 

If this is working as intended, is there a supported way of outputting multiple lines of pre-formatted text (without glue interpolation) while respecting the margins?

**Comment by gaborcsardi** [comment]
Yeah, this is a bug.

**Comment by tzakharko** [comment]
I have submitted a pull request to fix it (it simply splits verbatim text into lines before passing it to `style$fmt`). Also added a test for this. 

If you don't like this particular solution, I'm happy to improve on it.

**Comment by tzakharko** [comment]
Ah yes, sorry about that, I hope to have fixed it now. 

Another note: I am not sure whether it will correctly work on all platforms and across all inputs due to how new lines are handled. A more robust way would be to use something like `stri_split_lines()` but I am not sure that you want to add an additional dependency...

**Comment by tzakharko** [comment]
Fixed in b15c8b0e73c2735f1de95f32e616788a1a1e26a0
