### ISSUE TITLE
Preserve NA

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#148]
I think this should return `TRUE`:

``` r
x <- cli::col_blue(NA)
is.na(x)
#> [1] FALSE
```

<sup>Created on 2020-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gaborcsardi** [comment]
Oh, yeah, I guess coming from 
```r
paste(NA)
#> [1] "NA"
```

**Comment by gaborcsardi** [comment]
Unfortunately this is hard to fix, because `paste()` does not support this, and implementing an alternative of `paste()` that does support it will potentially break some code, thanks to the many peculiarities of `paste()`.

**Comment by gaborcsardi** [comment]
Considering that cli is usually for printing and formatting strings for printing, and that this is hard to fix properly, I suggest we don't fix it.

**Comment by hadley** [comment]
Ok. Sounds reasonable
