### ISSUE TITLE
How to combine spinner and status update?

### ISSUE THREAD

**Issue by ShixiangWang** [r-lib/cli#150]
I love features in this package. When I used it in my development, I find no good way to combine spinner and status update. Is there a good example of this?

**Comment by gaborcsardi** [comment]
It took a while, but the dev version now has some good ways. E.g.

```r
f <- function() {
  cli_progress_step("Downloading data", spinner = TRUE)
  for (i in 1:100) { cli_progress_update(); Sys.sleep(2/100) }
  cli_progress_step("Importing data", spinner = TRUE)
  for (i in 1:100) { cli_progress_update(); Sys.sleep(1/100) }
  cli_progress_step("Cleaning data", spinner = TRUE)
  for (i in 1:100) { cli_progress_update(); Sys.sleep(2/100) }
  cli_progress_step("Fitting model", spinner = TRUE)
  for (i in 1:100) { cli_progress_update(); Sys.sleep(3/100) }
}
f()
```

![Screen Recording 2021-06-25 at 15 50 50](https://user-images.githubusercontent.com/660288/123434996-5e2dbd80-d5cd-11eb-8bc2-0c7ddbbb4e08.gif)

**Comment by ShixiangWang** [comment]
Thanks. Love it
