### ISSUE TITLE
cli_alert_info() not showing in console before file.choose()

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/cli#151]
I have this code:

```r
cli_alert_info("Select location of your client ID file:") 
json <- file.choose()
```

The problem is the `file.choose()` launches before the message of the line above it  (??) so people don't know why the window is opening :)

When the file is chosen, the message does display.

Are there any workarounds?

p.s. this happens for cat() too so is an R thing, not cli.

**Comment by gaborcsardi** [comment]
It seems like a buffering issue. Try adding `flush(stdout())` after the message.

**Comment by MarkEdmondson1234** [comment]
That didn't do it.  I have resorted to using:

```r
cli_alert_info("Select location of your client ID file:") 
do_it <- menu(title = "Ready to download?", choices = c("Yes", "No"))
json <- file.choose()
```

**Comment by gaborcsardi** [comment]
I experimented a bit, it seems that this is the buffering of the GUIs. In Windows RGui you can turn it off in the menu or the config, and then it is good. 

I don't know if there is a way to force the printing. I also don't know if there is a way to turn off the buffering in RStudio.

For now I am closing this, will fix if we come across a way to force the output.

**Comment by gaborcsardi** [comment]
Ah, `flush.console()` seems to do it in Rgui, and also in R.app, regardless of the buffering setting. 

It does seem to work in RStudio, bug reported: https://github.com/rstudio/rstudio/issues/8040

**Comment by gaborcsardi** [comment]
I am reopening this, because we should document it, especially if they fix it in RStudio...
