### ISSUE TITLE
Should there be a cli_suppress function or similar?

### ISSUE THREAD

**Issue by jimhester** [r-lib/cli#156]
I think it would be somewhat common for users to want to suppress cli messages for a given chunk of code. Something like this maybe?

```r
cli_suppress <- function(expr) {
  withCallingHandlers(
    expr,
    cli_message = function(c) {
      invokeRestart("cli_message_handled")
    }
  )
}
```

**Comment by gaborcsardi** [comment]
You can now catch/suppress the `cliMessage` conditions, so I am closing this.

**Comment by halldc** [comment]
Hi @gaborcsardi - I found the vignette confusing on this point. I've been trying `suppressMessages(expr, classes = "cli_message")` without luck before discovering this issue. Perhaps we could mention the `cliMessage` class here:

https://github.com/r-lib/cli/blob/154f3215e458728a2155217a7f4897da5b8edea0/vignettes/semantic-cli.Rmd#L427-L443
