### ISSUE TITLE
`cli_format_method` not capturing in RMarkdown documents

### ISSUE THREAD

**Issue by rundel** [r-lib/cli#159]
The `cli_format_method` based approach mentioned [here](https://github.com/r-lib/cli/issues/152#issuecomment-631966493) works in an interactive session as well as when running via Rscript but does not when in the context of an RMarkdown document. See the example code below, the first two examples work as I would expect but with the RMarkdown document "hello world" is not captured by the `cli_format_method` and hence shows when x is declared and not when it is printed.

Running in the console:
```{r}
x = cli::cli_format_method(cli::cli_text("hello world"))

print(123)
print(cli:::is_interactive())
print(x)
```

```
> x = cli::cli_format_method(cli::cli_text("hello world"))
> 
> print(123)
[1] 123
> print(cli:::is_interactive())
[1] TRUE
> print(x)
[1] "hello world"
```

Running via Rscript:
```
$ Rscript cli_test.R
[1] 123
[1] FALSE
[1] "hello world"
```

Running via RMarkdown (`rmarkdown::render("cli_test.Rmd")`):

`cli_test.Rmd`:
``````md
---
output: github_document
---

```{r}
x = cli::cli_format_method(cli::cli_text("hello world"))

print(123)
print(cli:::is_interactive())
print(x)
```
``````

`cli_test.md`:
``````

``` r
x = cli::cli_format_method(cli::cli_text("hello world"))
```

    ## hello world

``` r
print(123)
```

    ## [1] 123

``` r
print(cli:::is_interactive())
```

    ## [1] FALSE

``` r
print(x)
```

    ## character(0)
``````

**Comment by rundel** [comment]
Digging a bit through the internals, it seems like when in RMarkdown we are getting to [`signalCondition`](https://github.com/r-lib/cli/blob/e3ca34656f5bb82df63bfc1c741e75acc79b13d9/R/internals.R#L85) in `clii__message` and then not progressing past it to the `cat`. However, in the Rscript context the `signalCondition` passes and the `cat` call occurs.

I am not anywhere close to understanding the internals around the signal passing but hopefully this narrows things down somewhat.

**Comment by rundel** [comment]
I have been able to come up with a work around by using `asciicast` chunks in my Rmd - this was modeled after cli's vignettes but figuring this out was non-obvious and the whole process feels a bit clunky and likely to cause issues downstream for Rmd documents that might be using packages that depend on cli.

**Comment by gaborcsardi** [comment]
This is really weird, it must be bug I think.

**Comment by gaborcsardi** [comment]
Actually, I don't really understand what you are trying to do here. 

The idea is that `cli_format_method()` is called from the print/format method, see the example in the manual. If I put that example in an Rmd file, it works fine.

Well, except that it creates a separate output block for every cli message, but we'll fix that in #170.

**Comment by gaborcsardi** [comment]
@rundel I am closing this, because it is not clear to me if there is an issue to fix. Please re-open if you think something is wrong. Thanks!

**Comment by rundel** [comment]
Sorry for missing the earlier comment - see below for an example of the weird behavior based on what I'm seeing with `ghclass`:

Using the following in an Rmd,
``````
```{r}
ghclass::github_test_token("bad")
```
``````

produces

``` r
ghclass::github_test_token("bad")
#> x Your GitHub PAT failed to authenticate.
#> API message: Bad credentials
#> API docs: https://docs.github.com/rest
#> Missing page:
#> └─GitHub API error (401): 401 Unauthorized
#>   ├─ 
#>   └─
```

versus when I run it in the console I get,

```r
ghclass::github_test_token("bad")
#> x Your GitHub PAT failed to authenticate.
#> └─GitHub API error (401): 401 Unauthorized
#>   ├─ API message: Bad credentials
#>   └─ API docs: https://docs.github.com/rest
```

this likely comes down to me assembling the error messages in a slightly awkward way with trying to use cli to "glue" strings together which are then printed later. I'm happy to link to the relevant sections of ghclass that wrap the cli stuff.

**Comment by gaborcsardi** [comment]
Thanks, I'll look at that!

**Comment by rundel** [comment]
If it helps the relevant sections for generating that error message tree is in [util_safely.R](https://github.com/rundel/ghclass/blob/185d4890d164c40cadd0a5974af1a27886dc431f/R/util_safely.R) and the cli wrappers are in [util_cli.R](https://github.com/rundel/ghclass/blob/185d4890d164c40cadd0a5974af1a27886dc431f/R/util_cli.R).

**Comment by gaborcsardi** [comment]
@rundel Can you pls try the latest GH commit?

**Comment by rundel** [comment]
That looks like it fixed it for me but with the minimal example and for the larger usage in the ghclass vignette.

**Comment by gaborcsardi** [comment]
You mean the vignette is still not completely fixed?

**Comment by rundel** [comment]
Sorry that was a bad typo - it is working as expected for both.

**Comment by gaborcsardi** [comment]
Great, thank for checking!
