### ISSUE TITLE
 Rules in ASCII

### ISSUE THREAD

**Issue by elinw** [r-lib/cli#166]
I'm not sure this is an issue, but I wanted to share it because it seems a bit strange.

I've been working on making skimr tests pass under testthat 3 which means that they match the output for `cli.unicode=FALSE`.  This impacted two things, ellipsis and rules. The ellipses was fine once I figured out that sometimes it is "~" and sometimes "...".

In terms of rules this file passes.
https://github.com/ropensci/skimr/blob/master/tests/testthat/dplyr/filter-skim.txt

You can see that the rendering is slightly different when it is a plain rule versus one with text.

```
-- Data Summary ------------------------
                           Values
Name                       iris  
Number of rows             150   
Number of columns          5     
_______________________ 
```
It's a subtle difference that did require me to change a lot of tests, but more important it's not what I would expect if I were rendering in the console.

If you think this is an issue you can see our code that uses cli in this file.
https://github.com/ropensci/skimr/blob/76d59f3c0424eccad272502d18c5d64f5974d3af/R/skim_print.R

**Comment by gaborcsardi** [comment]
Can you please include a reprex, including the output, and also tell me why the output is wrong? THanks.

**Comment by elinw** [comment]
Okay, now that I reproduced it, it's not a cli issue--source is elsewhere.
