### ISSUE TITLE
Allow collecting multiple widgets into the same message

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#170]

**Comment by gaborcsardi** [comment]
Maybe something like this would work:

```r
my_alert <- function(texts, .envir = parent.frame()) {
  cli::cli({
    cli::cli_alert(texts[1], wrap = TRUE, .envir = .envir)
    cli::cli_div(theme = list(.alert = list(`margin-left` = 2, before = "")))
    lapply(texts[-1], cli::cli_alert, wrap = TRUE, .envir = .envir)
    cli::cli_end()
  })
}
```

And this would send a single message, with all the content.

**Comment by gaborcsardi** [comment]
This could potentially deprecate `cli_format()`, maybe?

**Comment by jimhester** [comment]
I do this in readr if it helps with this utility function,

https://github.com/tidyverse/readr/blob/9fd116077ce8363c197ee5c414aadfb7058bde1a/R/utils.R#L78-L88

And example usage https://github.com/tidyverse/readr/blob/360f3fef03cf1bb4751e77cb36fae488d58c66de/R/col_types.R#L324-L331

**Comment by gaborcsardi** [comment]
Yeah, `cli_block()` is good name. Is it important to be able to signal the messages with `rlang::inform()`, btw?

**Comment by jimhester** [comment]
yeah, because I want them to print as non-red in RStudio interactively, so can't just use `message()`.

**Comment by gaborcsardi** [comment]
This is done in #233 now, just waiting for GHA come back to life.

I decided on the `cli()` name, because other candidates `cli_block()`, `cli_meta()` etc. were easy to mistake with a cli element. I.e. `cli_div()` vs. `cli_block()`.
