### ISSUE TITLE
has_color is not well detected in condition message

### ISSUE THREAD

**Issue by cderv** [r-lib/cli#196]
This follows some investigations to close https://github.com/yihui/knitr/issues/1805 with an issue in rlang error coloring when rendering an Rmd file. 

See the last reprex at https://github.com/yihui/knitr/issues/1805#issuecomment-581146557

It seems `has_color` does not return the same result depending how the error message is created.

See this Rmd results 

<details><summary>Rmd source</summary>

````r
---
title: "crayon in Rmd"
output: md_document
---
Check some `has_color` success conditions
```{r}
crayon_sitrep <- function() {
  paste(
    "\n",
    "crayon:::rstudio_with_ansi_support() :", 
    crayon:::rstudio_with_ansi_support(), "\n",
    "sink.number() :", sink.number(), "\n",
    "isatty(stdout()) :", isatty(stdout())
  )
}
```

Building error this way, `sink.number > 0` so result is not TRUE even in RStudio

```{r, error = TRUE}
er <- errorCondition(
  message = crayon_sitrep())
stop(er)
```

However, using a specific class for a condition and definining a special method
for `conditionMessage`, `sink.number()` is equal to 0 (reset ?) and `has_color` 
see RStudio is used. That why we get TRUE for color support. 

```{r, error = TRUE}
conditionMessage.barfoo <- function(c) crayon_sitrep()
stop(errorCondition("", class = "barfoo"))
```

## With rlang

This above is causing issue with rlang error too,and thus the tidyverse in
Rmarkdown.

```{r, error = TRUE}
rlang::abort(crayon_sitrep())
```

```{r, error = TRUE}
conditionMessage.foobar <- function(cnd) crayon_sitrep()
rlang::abort(.subclass = "foobar")
```
````
</details>

<details><summary>Resulting markdown output with results</summary>

Check some `has_color` success conditions

```r
crayon_sitrep <- function() {
  paste(
    "\n",
    "crayon:::rstudio_with_ansi_support() :", 
    crayon:::rstudio_with_ansi_support(), "\n",
    "sink.number() :", sink.number(), "\n",
    "isatty(stdout()) :", isatty(stdout())
  )
}
```

Building error this way, `sink.number > 0` so result is not TRUE even in RStudio

```r
er <- errorCondition(
  message = crayon_sitrep())
stop(er)
```

```
## Error: 
##  crayon:::rstudio_with_ansi_support() : TRUE 
##  sink.number() : 1 
##  isatty(stdout()) : FALSE
```

However, using a specific class for a condition and definining a special method
for `conditionMessage`, `sink.number()` is equal to 0 (reset ?) and `has_color` 
see RStudio is used. That why we get TRUE for color support. 

```r
conditionMessage.barfoo <- function(c) crayon_sitrep()
stop(errorCondition("", class = "barfoo"))
```

```
## Error: 
##  crayon:::rstudio_with_ansi_support() : TRUE 
##  sink.number() : 0 
##  isatty(stdout()) : FALSE
```

## With rlang

This above is causing issue with rlang error too,and thus the tidyverse in
Rmarkdown.

```r
rlang::abort(crayon_sitrep())
```

```
## Error: 
##  crayon:::rstudio_with_ansi_support() : TRUE 
##  sink.number() : 1 
##  isatty(stdout()) : FALSE
```

```r
conditionMessage.foobar <- function(cnd) crayon_sitrep()
rlang::abort(.subclass = "foobar")
```

```
## Error: 
##  crayon:::rstudio_with_ansi_support() : TRUE 
##  sink.number() : 0 
##  isatty(stdout()) : FALSE
```

</details>

I think `has_color()` should always return FALSE when code is executed from an R markdown chunk using interactively `rmarkdown::render()`, `knitr::knit()` or non interactively using the Knit button.
Depending on their output format, user could opt-in as they wish (see https://github.com/r-lib/crayon/issues/24#issuecomment-581068792 for html output for example)

The checks about `sink` should have been enough but it seems that it is not, due to this special behavioir in `conditionMessage`. 🤷‍♂ 

Could be related in a way to r-lib/crayon#80 but seems different.

**Comment by gaborcsardi** [comment]
This will is fixed in cli with e83f3d25c8683cdfc164f20eae76b5b3a59d70b1
It will be fixed in crayon as well, once I port back the color detection changes there.

**Comment by gaborcsardi** [comment]
This is now fixed in dev crayon as well. We'll have crayon and cli releases after the break. (I don't want to release now incase I mess something up.)

**Comment by cderv** [comment]
Thanks Gabor ! 
Next year is completely fine. I checked that reprex in knitr's issue is now fixed with these dev version. 
Thanks.
