### ISSUE TITLE
Should has_color return TRUE if stderr is a tty?

### ISSUE THREAD

**Issue by jimhester** [r-lib/cli#198]
Currently `has_color()` checks if `stdout()` is a tty, and if it is not then colors are disabled.

https://github.com/r-lib/crayon/blob/84be62074ad5b3ede54dd035ef4003f808f34f12/R/has_color.r#L64

However it is possible users would still want color if stdout is redirected (so is no longer a tty) but stderr is still a tty and the colors are being used in messages to stderr. In fact perhaps it is actually more common for colors to be used in output to stderr than stdout?

I am not sure how best to address this, as crayon has no way of knowing where the output is going to, but the current behavior seems too conservative.

**Comment by gaborcsardi** [comment]
`cli::num_ansi_colors()` takes a stream now, so you can check separately for stdout and stderr. The default is the stream that cli would use by default for output.
