### ISSUE TITLE
Publicize crayon.enabled option

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#200]
Context: I'm writing tests for a crayon-using package and want the joy of testing the UI w/o ANSI escape codes. I struggle to remember how to turn crayon off ...

I end up reminding myself re: `crayon.enabled` by reading source.

Can we advertise `crayon.enabled` in some high-level doc? Maybe README? I'd be happy to make a PR.

**Comment by gaborcsardi** [comment]
In general it is not a good idea to have an env var or option to force turn on colors, because options are inherited by knits and other `sink()`-ed environments, and env vars are inherited by subprocess as  well. It is perfectly fine to turn them off, OTOH.

**Comment by gaborcsardi** [comment]
I added it to the new FAQ: https://github.com/r-lib/cli/commit/ae4a5acd52036f0042d0e33c4dfc5f4c171137f1
