### ISSUE TITLE
Colors in R Session Running Under Rstudio Terminal

### ISSUE THREAD

**Issue by brodieG** [r-lib/cli#201]
This seems related to r-lib/crayon#56, except this is running R from an Rstudio terminal, instead of the normal Rstudio console.  Setting forget to TRUE fixes it.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/6105908/51286317-7c387200-19c0-11e9-90b6-e39fc46204d9.png">

This is a pretty obscure use case, so probably not worth dealing with unless its trivial to fix.  The `tempfile` thing is unrelated.

**Comment by gaborcsardi** [comment]
This should be fixed now, at least for the version in cli, I think.
