### ISSUE TITLE
Crayon prints escape sequences, does not apply colors in neovim-qt :terminal

### ISSUE THREAD

**Issue by wngrtn** [r-lib/cli#203]
I am on Win10, neovim 3.1 and neovim-qt. When I use `:terminal` to run `ls --color=always` I get nicely colored output. When I open `R` and run `library(tidyverse)`, which uses `crayon`, I see escape sequences instead of colors:

    -- ?[1mAttaching packages?[22m --------------------------------------- tidyverse 1.2.1 --
    ?[32mv?[39m ?[34mggplot2?[39m 3.0.0     ?[32mv?[39m ?[34mpurrr  ?[39m 0.2.5
    ?[32mv?[39m ?[34mtibble ?[39m 1.4.2     ?[32mv?[39m ?[34mdplyr  ?[39m 0.7.7
    ?[32mv?[39m ?[34mtidyr  ?[39m 0.8.1     ?[32mv?[39m ?[34mstringr?[39m 1.3.1
    ?[32mv?[39m ?[34mreadr  ?[39m 1.1.1     ?[32mv?[39m ?[34mforcats?[39m 0.3.0

Is neovim-qt :terminal on Windows not supported or am I doing something wrong? If this is not the right place to address this issue, could you point in the right direction?

**Comment by gaborcsardi** [comment]
It seems that `echo` indeed turns on colors. E.g. after running this:
```r
system2("cmd", c("/c", "echo"))
```
The colors work. This will produce some output, so it is awkward to run it.

I don't know if there is a way to query `ENABLE_VIRTUAL_TERMINAL_PROCESSING` without compiled code, so I am unsure what to do with this. We could maybe include a small Windows binary that can query and set it.
