### ISSUE TITLE
Options to customize default colors

### ISSUE THREAD

**Issue by bwiernik** [r-lib/cli#204]
I'm colorblind and use a dark theme in my editor. Whenever a package uses `crayon::red()`, I can't see the text at all. Would it be possible to add an options system to let users to specify different colors to use for the base `crayon` color functions? For example, the option to specify `options(crayon.red = "coral3")` to use the `"coral3"` color instead of the base R `"red"` color for red text. 

If this is reasonable, I would be happy to do a pull request.

**Comment by gaborcsardi** [comment]
@bwiernik i am sorry this takes so long: #329. 

I will merge it after the CI checks and then you can try it easier, if you are interested. 

The `dichro` palette is hopefully better for everyone:

```r
options(cli.palette = "dichro")
cli::ansi_palette_show()
```

This is how it looks currently:

<img width="688" alt="Screen Shot 2021-08-06 at 15 49 42" src="https://user-images.githubusercontent.com/660288/128521060-be75b2d7-2b7f-4841-8a36-3c313e089a08.png">

The cli package will supersede crayon, but I can port this back to crayon as well, so the hundreds of packages currently depending on crayon will use the same palette.

Suggestions for palette changes and new palettes are most welcome! Thanks, and sorry again.

**Comment by gaborcsardi** [comment]
The PR closed this, I did not mean to close it just yet.

**Comment by bwiernik** [comment]
Wow! This is awesome! The built in palettes work great for me. If you could back port this to crayon, that would be amazing!

**Comment by bwiernik** [comment]
And well worth the wait! Really appreciate you implementing something as robust and flexible as this!

**Comment by gaborcsardi** [comment]
@bwiernik Thanks for the feedback. I'll go ahead with this then.

**Comment by bwiernik** [comment]
The only thought I have on the palettes is that setting black and white as actual black and white versus dark/light grey makes it difficult to use those palettes with dark/light themes. It might make more sense to use greys in all of the palettes for those two.

**Comment by gaborcsardi** [comment]
Yeah. I think in practice we need to avoid just `col_black()` and `col_white()` for text unless we know the background color. (Because we set that as well, or we are in RStudio where we can query the theme.)
