### ISSUE TITLE
Export crayon:::is_r_color and crayon:::style_from_r_color?

### ISSUE THREAD

**Issue by aedobbyn** [r-lib/cli#207]
Thanks for the amazing package!

A new package [`multicolor`](https://github.com/aedobbyn/multicolor) makes heavy use of `crayon`. There is a [PR](https://github.com/sckott/cowsay/pull/59#issuecomment-407264843) for it to be integrated into the [`cowsay`](https://github.com/sckott/cowsay) package by @sckott and friends.

A new `cowsay` release to CRAN would also require that `multicolor` be on CRAN. Currently `multicolor` uses two internal `crayon` functions, [`is_r_color`](https://github.com/aedobbyn/multicolor/blob/master/R/multi_color.R#L64) and [`style_from_r_color`](https://github.com/aedobbyn/multicolor/blob/master/R/utils.R#L33) and so wouldn't pass a CRAN check. 

Would it be possible to export these two functions in the next release of `crayon`? If you'd rather not export and have other ideas I'd be totally open to them. `is_r_color` would be feasible to copy the code for, but `style_from_r_color` wouldn't be, imo.

**Comment by gaborcsardi** [comment]
I guess these are not needed any more, so I am closing this.

**Comment by aedobbyn** [comment]
yep! totally fine
