### ISSUE TITLE
Color output in Rmarkdown documents / notebooks

### ISSUE THREAD

**Issue by x1o** [r-lib/cli#209]
Is it possible to render color `cli` output in R notebooks? Currently I have, e.g.:

Console:
![Screenshot from 2020-12-30 14-35-23](https://user-images.githubusercontent.com/3007504/103348846-4c4ee000-4aac-11eb-9746-344bea51ba08.png)

R notebook:
![Screenshot from 2020-12-30 14-35-30](https://user-images.githubusercontent.com/3007504/103348845-4bb64980-4aac-11eb-9e86-e24e1186bd4a.png)

This is cli-2.2.0 on Ubuntu.

**Comment by gaborcsardi** [comment]
This should be fixed in dev cli, which turns off colors in knitr

**Comment by x1o** [comment]
But it hasn't been yet, right?

Is there perhaps a workaround for now?

**Comment by x1o** [comment]
Oh, I see, it has been implemented in e83f3d25c8683cdfc164f20eae76b5b3a59d70b1

Sadly, the fix won't work for notebooks (only for Rmarkdown documents) :(

**Comment by gaborcsardi** [comment]
I am afraid you need to be more specific, because it does seem to work for me.

<img width="755" alt="Screen Shot 2020-12-30 at 14 20 35" src="https://user-images.githubusercontent.com/660288/103357182-743d4400-4aaa-11eb-8184-f1dc57ce7d53.png">

**Comment by x1o** [comment]
I reckon in the rendered notebook (if you "Preview" it) you'll still see raw ANSI escapes.

**Comment by gaborcsardi** [comment]
> I reckon in the rendered notebook (if you "Preview" it) you'll still see raw ANSI escapes.

I don't, actually.

<img width="287" alt="Screen Shot 2020-12-30 at 14 57 22" src="https://user-images.githubusercontent.com/660288/103359192-5de5b700-4aaf-11eb-9958-d3a5f2de1522.png">

**Comment by x1o** [comment]
Cool. Do you have `output: html_notebook`? If so, which relevant package versions can I check (apart from `cli`)?

![Screenshot from 2020-12-30 18-01-27](https://user-images.githubusercontent.com/3007504/103359488-13713400-4ac9-11eb-9c7f-2c979cf0caa6.png)
![Screenshot from 2020-12-30 18-00-52](https://user-images.githubusercontent.com/3007504/103359495-1409ca80-4ac9-11eb-867b-c2ed035f4353.png)

**Comment by gaborcsardi** [comment]
No other packages are involved in this I think. But it might depend on the RStudio version.

**Comment by x1o** [comment]
Oh you are right, I'm still using 1.2.5042, which is a little outdated.

Thank you!
