### ISSUE TITLE
Importance of the cli app should be much more obvious

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#210]
A companion issue to https://github.com/r-lib/testthat/issues/1296 based on reprex's recent switch to testthat 3e (including snapshot tests of user-facing messaging) and the use of cli for the UI. 

I had a very tough time getting saved snapshots that did **not** contain Unicode and ANSI escapes.

This PR https://github.com/tidyverse/reprex/pull/351 in reprex shows the problem. The use of Unicode and ANSI colours by cli inside a test is, by default, **not** under the control of the current values of seemingly relevant options, nor is it under the control of whatever `cli::cli_sitrep()` reports.

Instead, if a cli "app" happens to already be running, *its* state is what matters. It's hard to predict what causes the cli app to start. From https://github.com/r-lib/testthat/pull/1295 in testthat, it seems one is not running prior to the first snapshot test involving cli, but https://github.com/tidyverse/reprex/pull/351 in reprex shows the opposite. Does it have something to do with the nature of the cli calls inside the package?

How did I know to bark up the "app" tree? Conversing with @hadley elsewhere about my frustrations, he suggested that I explicitly call `cli::start_app()` in the affected tests (the ones snapshotting code that contains cli calls) and this resolved the problem.

Possible things to do in cli:

* More documentation around the existence of cli apps and their significance. Which cli functions are influenced by the app and which are not? What causes an app to start and set its Unicode/colour state?
* It feels like `cli::cli_sitrep()` should report the settings actually in force and, perhaps, reflect *why* they are in force. Or report these options AND whether an app is running and what its settings are.
* Recommend the use of `cli::start_app(.auto_close = TRUE)` in any test that calls cli, where there are expectations about the cli output (it's possible that `testthat::test_that()` will take care of this).

**Comment by gaborcsardi** [comment]
This is actually a bug / thinko in the handling of themes. The only thing an app remembers is the stack of themes. I.e. it does not remember the "unicode state" and the "ansi color state". 

However, the default theme defines some prefixes too early, so they are not evaluated at "formatting time", but already when the theme is created. Which is usually when an app is created.

**Comment by jennybc** [comment]
Interesting! Well, in any case, I'm glad this issue was productive.

Is this the "build time" vs. "run time" issue with yet another new look? It truly comes in so many forms 😂
