### ISSUE TITLE
Multi-line alerts (not just from wrapping, but explicit line breaking)

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#211]
Is there a better way to achieve this? Where by "this" I mean putting the `path` text on its own line, indented nicely with respect to `header`. This looks the way I want but feels pretty goofy.

``` r
reprex_path <- function(header, path, .envir = parent.frame()) {
  cli::cli_alert_success(header, .envir = .envir)
  cli::cli_ul()
  cli::cli_li()
  cli::cli_text("{.file {path}}")
}

reprex_path("Lorem ipsum dolor sit amet", "path/to/a/file")
#> ✓ Lorem ipsum dolor sit amet
#>   path/to/a/file
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<img width="693" alt="Screen Shot 2021-01-14 at 4 31 16 PM" src="https://user-images.githubusercontent.com/599454/104665360-f40c0680-5685-11eb-9ec2-462298d963ea.png">

**Comment by gaborcsardi** [comment]
If you use `wrap = TRUE`, then the message is auto-wrapped, but you can't request a newline otherwise, I am afraid:

```r
❯ cli::cli_alert_success("Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet  Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet {.file /path/to/file}", wrap = TRUE)
✔ Lorem ipsum dolor sit amet Lorem ipsum dolor sit amet Lorem ipsum dolor sit
  amet Lorem ipsum dolor sit amet /path/to/file
```

It would make sense to add it, though.

**Comment by gaborcsardi** [comment]
For a starter we call use glue with `.trim = FALSE`. This probably makes sense, because otherwise the glue and the cli formatting might non-trivially interfere. Changing to `.trim = FALSE` does not break any test cases, FWIW.

With this we can write:
```r
❯ cli_alert_success("hello\n  world!")
✔ hello
  world!
```

Ideally we should not need to hardcode the two spaces here, but `cli_alert*()` hardcodes it currently as well.

**Comment by gaborcsardi** [comment]
If you set the left margin instead of `before`, then wrapping will work as well:

``` r
my_alert <- function(texts, .envir = parent.frame()) {
  cli::cli_alert(texts[1], wrap = TRUE, .envir = .envir)
  cli::cli_div(theme = list(.alert = list(`margin-left` = 2, before = "")))
  lapply(texts[-1], cli::cli_alert, wrap = TRUE, .envir = .envir)
  cli::cli_end()
}

blah <- "whatnot"
x <- c(
  "This is the main {.strong headline} of the alert",
  "but maybe I also need to show a path {.file {fs::path_home()}}",
  "and say more {.emph stuff} and {.field {blah}}"
)
my_alert(x)
#> → This is the main headline of the alert
#>   but maybe I also need to show a path /Users/gaborcsardi
#>   and say more stuff and whatnot

options(cli.width = 40)
my_alert(x)
#> → This is the main headline of the
#>   alert
#>   but maybe I also need to show a path
#>     /Users/gaborcsardi
#>   and say more stuff and whatnot
options(cli.width = 40)
my_alert(x)
#> → This is the main headline of the
#>   alert
#>   but maybe I also need to show a path
#>     /Users/gaborcsardi
#>   and say more stuff and whatnot
```

<sup>Created on 2021-03-17 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jennybc** [comment]
Interesting! It feels like we're getting an extra level of indentation when wrapping kicks in.

<img width="569" alt="Screen Shot 2021-03-17 at 4 27 44 PM" src="https://user-images.githubusercontent.com/599454/111551691-0239da00-873e-11eb-9759-698ed52152c4.png">

**Comment by gaborcsardi** [comment]
Yes, because otherwise there is no way to tell if a line is a continuation or not. This is currently hard-coded in alerts. We could make it configurable, or use something else for the "body" of the alerts, or use the width of "before" to set the indentation by default. I think the latter is reasonable, nevertheless.

**Comment by jennybc** [comment]
> Yes, because otherwise there is no way to tell if a line is a continuation or not

True, although in my usage, I tend to start lines with an upper case letter, which does (weakly) indicate the start of a line.

I don't purposefully write long lines that will need wrapping. My preference for short lines, one line per fact, is, in fact, how we even got here.

But I have to allow for long lines (so I want `wrap = TRUE`) because sometimes they happen due to injecting text that is out of my control (e.g., file name or error description from the API).

I suspect this multi-line variant of `cli_alert()` should get its own name. I think the existing `cli_alert()`s, which are very oriented towards 1 short message, make a lot of sense and it would be a shame to complicate them.

**Comment by gaborcsardi** [comment]
With https://github.com/r-lib/cli/commit/f2b8408fd264fdaa3e64d176b717c19ee8fbee13

```r
❯ options(cli.width = 40)
❯ my_alert(x)
→ This is the main headline of the
  alert
  but maybe I also need to show a path
  /Users/gaborcsardi
  and say more stuff and whatnot
```

**Comment by jennybc** [comment]
Yeah the version that uses ``list(`margin-left` = 2, before = "")`` is shaping up nicely (and is clearly better than my initial workaround of `list(before = "  ")`). I've changed the text to reflect my capitalization habits.

``` r
my_alert_margin <- function(texts, .envir = parent.frame()) {
  cli::cli_alert(texts[1], wrap = TRUE, .envir = .envir)
  cli::cli_div(theme = list(.alert = list(`margin-left` = 2, before = "")))
  lapply(texts[-1], cli::cli_alert, wrap = TRUE, .envir = .envir)
  cli::cli_end()
}

my_alert_before <- function(texts, .envir = parent.frame()) {
  cli::cli_alert(texts[1], wrap = TRUE, .envir = .envir)
  cli::cli_div(theme = list(.alert = list(before = "   ")))
  lapply(texts[-1], cli::cli_alert, wrap = TRUE, .envir = .envir)
  cli::cli_end()
}

blah <- "whatnot"
name <- "jenny"
x <- c(
  "This is the main {.strong headline} of the alert",
  "But maybe I also need to show a path {.file {fs::path_home()}}",
  "And say more {.emph stuff} and {.field {blah}}"
)

my_alert_margin(x)

withr::with_options(
  list(cli.width = 40),
  my_alert_margin(x)
)

my_alert_before(x)

withr::with_options(
  list(cli.width = 40),
  my_alert_before(x)
)
```

I'll show a screenshot for the full effect.

<img width="585" alt="Screen Shot 2021-03-18 at 8 55 01 AM" src="https://user-images.githubusercontent.com/599454/111656423-bf244900-87c7-11eb-99b3-74a5f0ffd509.png">

**Comment by jennybc** [comment]
Name-wise, if you agree this should be separate from `cli_alert()` ... bulletin? advisory? memo?

Or maybe this is just expanding the functionality of `cli_alert()` to accommodate a vector of lines via`text`.

**Comment by gaborcsardi** [comment]
Yeah, I think we can add this to the existing alerts, maybe with `details = ...`.
