### ISSUE TITLE
Terminal output unreadable in Firefox

### ISSUE THREAD

**Issue by llrs** [r-lib/cli#220]
Hi, nice package! I found particularly interesting the vignette about moving from `usethis::ui_*` functions.

However, all the terminal output I see on my usual browser (Firefox 85.0.1 on ubuntu 20.04) is distorted (not sure how it is rendered and not displayed as in usethis vignettes):

![Screenshot from 2021-02-11 19-32-01](https://user-images.githubusercontent.com/6818218/107681815-d8554980-6c9f-11eb-87bb-795f6b163051.png)

Each day there are less Firefox users, but still it would be nice to be able to use it. 
Thanks.

**Comment by gaborcsardi** [comment]
This is some font issue, it looks like this in my Firefox:

<img width="878" alt="Screen Shot 2021-02-11 at 20 20 15" src="https://user-images.githubusercontent.com/660288/107687491-d17e0500-6ca6-11eb-8963-f6b43486b2a7.png">

Do you have some custom font setup?

These are the fonts of the SVGs:
```
"Fira Code",Monaco,Consolas,Menlo,"Bitstream Vera Sans Mono","Powerline Symbols",monospace
```

**Comment by llrs** [comment]
Many thanks for the quick reply. I think I don't have a custom font setup, I have the default DejaVu Serif and haven't worked with fonts. [Some](https://stackoverflow.com/a/14419226/2886003) said I needed to clear the cache but I still see the same. ([Related](https://stackoverflow.com/questions/21171709/)?)
