### ISSUE TITLE
Warning or error on `cli_end` when no containers present

### ISSUE THREAD

**Issue by rundel** [r-lib/cli#223]
This would mainly be a very small quality of life improvement to help with debugging - I was bit by this because I forgot that `cli_ol` or `cli_ul` with `items` immediately creates and closes the container and so I was a bit perplexed initially by the behavior of code like the following:

```r
test = function() {
  l1 = cli::cli_ol("Level 1")
  cli::cli_li("Node")
  cli::cli_end(l1)
}

test()
#> 1. Level 1
#> ● Node
```

The behavior makes sense given the function documentation, but this is an easy mistake to make and having a warning or error about trying to end/close a non-existant container (similar to how `dev.off` behaves) might be helpful.

(Last issue for now, I promise)

**Comment by gaborcsardi** [comment]
My main issue with such a warning is that, most cli container auto-close, and I am afraid that it is easy to call `cli_end()` on a non-existing container, especially after some error which causes an auto-close.

This is probably hard to get right for all cases, maybe we need some "strict-close" option for debugging?

**Comment by rundel** [comment]
That makes sense to me - I think the status quo is reasonable as things "just work", so having the ability to set an option to enable strict checking for debugging purposes would cover this edge case.

**Comment by gaborcsardi** [comment]
It looks like this:
```r
❯ cli_end()

❯ Sys.setenv("CLI_DEBUG_BAD_END" = "true")
❯ cli_end()
Warning message:
In clii__container_end(app, id) : No cli container to close

❯ cli_end("foo")
Warning message:
In clii__container_end(app, id) : Can't find cli container 'foo' to close
```

Will this do? Btw. you might also find the new `cli_debug_doc()` (internal) function useful:

```r
❯ cli_debug_doc()
<cli document>
<body id="body">

❯ cli_ol()
❯ cli_li()
❯ cli_par()
❯ cli_debug_doc()
<cli document>
<body id="body">
<ol id="cli-22613-7">
<li id="cli-22613-11">
<par id="cli-22613-12">

❯ cli_debug_doc()[]
   tag           id class theme       styles
1 body         body             list(fs_....
2   ol  cli-22613-7             list(fs_....
3   li cli-22613-11             list(fs_....
4  par cli-22613-12             list(fs_....
```

**Comment by rundel** [comment]
That looks great, particularly the `cli_debug_doc()`
