### ISSUE TITLE
install.packages('cli') from `source` or `binary` and 'pkgbuild' dependencies 

### ISSUE THREAD

**Issue by gwd999** [r-lib/cli#224]
It looks as if 'cli' package installation fails because package 'cli' is not available/installed? 
Running R-4.0.4 on CMD line with `R --vanilla` on Windows 10 PRO 20H2.   
Originally I ran into this during `update.packages()`   
Then I fiddled around with `remove.packages('cli')` plus remove.packages('pkgbuild')` because of some dependecies between those two. 
sort of then trying a fresh `cli` package installation.   
R the seems to default to `type = 'source'` below and throws the described `loadNamespace- Error`   

```
There is a binary version available but the source version is later:
    binary source needs_compilation
cli  2.3.0  2.3.1             FALSE

installing the source package 'cli'

trying URL 'https://cran.wu.ac.at/src/contrib/cli_2.3.1.tar.gz'
Content type 'application/x-gzip' length 134171 bytes (131 KB)
downloaded 131 KB

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called 'cli'
Calls: local ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

The downloaded source packages are in
        'C:\Users\userid\AppData\Local\Temp\RtmpAhV2it\downloaded_packages'
Warning message:
In install.packages("cli") :
  installation of package 'cli' had non-zero exit status
```
Workaround solution: `install.packages('cli', type = 'binary')` which will install version `2.3.0` BUT because of inter-dependencies between `cli` and `pkgbuild` (pkgbuild importing cli, therefore cannot unload) updating cli even with fresh restart of `R --vanilla` and neither cli nor pkgbuild showing up in `search()` runs into ` namespace 'cli' is imported by 'pkgbuild' so cannot be unloaded` issues. 
Is this expected/intentional behaviour?

**Comment by gaborcsardi** [comment]
This is not an issue with cli. Either you ended up with some broken packages, or it is a bug in `install.packages()`. In any case, can you try installing with pak:

```r
install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
pak::pkg_install("cli")
```

**Comment by gwd999** [comment]
> This is not an issue with cli. Either you ended up with some broken packages, or it is a bug in `install.packages()`. In any case, can you try installing with pak:
> 
> ```r
> install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
> pak::pkg_install("cli")
> ```

Ok - will test out a few variations of install packages based on yr suggestion. 
Gonna come back w results in an UPDATE ...

**Comment by MaxineTheCat** [comment]
Not sure if this helps but I got this error from cli when trying to build another package: 
```
Error in if (num_ansi_colors() > 1) { : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... cat_line -> paste0 -> rule -> apply_style -> <Anonymous>
Execution halted
```

might be unrelated though

**Comment by gaborcsardi** [comment]
@gwd999 So you try to run the two lines of code here: https://github.com/r-lib/cli/issues/224#issuecomment-787416013

@MaxineTheCat I think that's the cli counterpart of https://github.com/r-lib/crayon/issues/112 and should be fixed in the latest version.

**Comment by gwd999** [comment]
> @gwd999 Can you try to run the two lines of code here: [#224 (comment)](https://github.com/r-lib/cli/issues/224#issuecomment-787416013)
> 
> @MaxineTheCat I think that's the cli counterpart of [r-lib/crayon#112](https://github.com/r-lib/crayon/issues/112) and should be fixed in the latest version.

Hi Gabor, 

as mentioned above running these two lines delivers: 
```
trying URL 'https://r-lib.github.io/p/pak/dev/bin/windows/contrib/4.0/pak_0.1.2.9001.zip'
Content type 'application/zip' length 13786928 bytes (13.1 MB)
downloaded 13.1 MB
files ‘DESCRIPTION’, ‘Meta/package.rds’ have the wrong MD5 checksums
```

**Comment by gaborcsardi** [comment]
Yes, that's the first line, but it is the second line that actually installs cli, so please run that as well, and show me the output. E.g. I get this:

```
❯ install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
Installing package into ‘/Users/gaborcsardi/Library/R/4.0/library’
(as ‘lib’ is unspecified)
trying URL 'https://r-lib.github.io/p/pak/dev/bin/macosx/contrib/4.0/pak_0.1.2.9001.tgz'
Content type 'application/octet-stream' length 6754251 bytes (6.4 MB)
==================================================
downloaded 6.4 MB


The downloaded binary packages are in
	/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T//Rtmp3BZjlt/downloaded_packages

❯ pak::pkg_install("cli")

→ Will install 1 package.
→ Will download 1 CRAN package (469.80 kB).
+ cli   2.3.1  ⬇ (469.80 kB)

ℹ Getting 1 pkg (469.80 kB)
✔ Got cli 2.3.1 (macos) (469.80 kB)
✔ Downloaded 1 package (469.80 kB) in 1.2s
✔ Installed cli 2.3.1  (36ms)
✔ 1 + 2 pkgs | kept 2, updated 0, new 1 | downloaded 1 (469.80 kB) 2s
```

**Comment by gwd999** [comment]
Ahhh - I only now noticed that depsite the MD5 issue it still installs the pak package 
```
pak::pkg_install("cli")
v Updated metadata: 4.41 MB in 14 files.                                  
v Updating local metadata database ... done                               
                                                                          
> Will update 1 package.
> Will download 1 package with unknown size.
+ cli 2.3.0 > 2.3.1 [dl]

! cli is loaded in the current R session, you probably need to restart R after
  the installation.
```

**Comment by gwd999** [comment]
Hmm - so this fixes the problem; still what do think - is there a need to adjust something so that one can use the "normal" update process?

**Comment by gaborcsardi** [comment]
> Hmm - so this fixes the problem; still what do u think - is there a need to adjust something so that one can use the "normal" update process?

In cli? No, I don't think so. I am not sure why it did not work for you, maybe you use load and set up prompt in your profile in non-interactive sessions as well, but I am only guessing. If you load packages from your profile that can easily trip up `install.packages()`.

**Comment by gwd999** [comment]
Final comment - I had the same issues with `R --vanilla`  in a command line session.

**Comment by gaborcsardi** [comment]
> I had the same issues with a R --vanilla session in a simple windows command prompt

`install.packages()` starts a new session when installing the package and that might load your profile anyway.

**Comment by gwd999** [comment]
> > I had the same issues with a R --vanilla session in a simple windows command prompt
> 
> `install.packages()` starts a new session when installing the package and that might load your profile anyway.

The moment I wrote my remark I realized this could potentially be the case - thanx for clarifying/confirming me that. 
Thanks a lot - sorry to have nagged you with this . 
Have a nice day, stay safe, stay home and keep up the great work.

**Comment by gaborcsardi** [comment]
No worries. pak works around these issues, so you can try it again if you run into installation failures.
