### ISSUE TITLE
Add inline class for `class` to the default theme

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#236]
It feels like we have a fairly strong convention for formatting class like `<foo>` or `<foo/bar/baz>`. And I'm pretty sure @Hadley advocates for this.

Assuming I'm right, I'd love to see such a class added to the default theme. Maybe `{.cls {class(x)}}`?

**Comment by hadley** [comment]
Yup, confirmed.

**Comment by jennybc** [comment]
When `class(x)` has length greater than one, what's the convention?

Do we only present the first element of `class(x)`?

If we present all elements of `class(x)` or just the extremes, do they appear in order or in reverse order?

I notice that rlang tends to do `error/{class(err)[[1]]}` for error subclasses. So ... that suggests presenting (morally, at least) the last element, then the first element. Reverse order and just the extremes.

``` r
f <- function(x, reverse = FALSE) {
  cls <- if (reverse) rev(class(x)) else class(x)
  glue::glue("<{cls}}>", cls = glue::glue_collapse(cls, sep = "/"))
}

x <- tibble::as_tibble(iris)
f(x)
#> <tbl_df/tbl/data.frame}>
f(x, reverse = TRUE)
#> <data.frame/tbl/tbl_df}>

rlang::abort("oops!", class = c("alfa", "bravo"))
#> Error: oops!
rlang::last_error()
#> <error/alfa>
#> oops!
#> Run `rlang::last_trace()` to see the full context.

err <- rlang::catch_cnd(
  rlang::abort("oops!", class = c("alfa", "bravo"))
)
f(err)
#> <alfa/bravo/rlang_error/error/condition}>
f(err, reverse = TRUE)
#> <condition/error/rlang_error/bravo/alfa}>
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by gaborcsardi** [comment]
I think we can let the developer decide which elements to show. I would think that the first element should be usually enough, so you would just do this:

```
"{.cls {xx[1]}}"
```
