### ISSUE TITLE
tree() throws warning if passed a tibble

### ISSUE THREAD

**Issue by cjyetman** [r-lib/cli#238]
The `cli::tree()` function throws a (presumably) undesirable warning if it's passed a tibble instead of a data frame (presumably, a likely use case). It's caused by https://github.com/r-lib/cli/blob/bc066c1c429b4e4d4dceb6bda6cb1bd15db57877/R/tree.R#L117
where `data$trimmed` returns `NULL` as expected but also a warning if `data` is a tibble. There are numerous obvious, easy ways to work around that, so I won't bother suggesting a solution/PR.

``` r
data <- data.frame(
  stringsAsFactors = FALSE,
  package = c("A", "B", "C"),
  dependencies = c("B", "C", "")
)

cli::tree(data)
#> A
#> └─B
#>   └─C

cli::tree(tibble::as_tibble(data))
#> Warning: Unknown or uninitialised column: `trimmed`.
#> A
#> └─B
#>   └─C

data$trimmed
#> NULL

tibble::as_tibble(data)$trimmed
#> Warning: Unknown or uninitialised column: `trimmed`.
#> NULL
```

**Comment by gaborcsardi** [comment]
Thanks! Do you want to submit a PR? No pressure, just asking. :)

**Comment by cjyetman** [comment]
I feel like this is one of those things that there are so many ways of fixing that it will come down more to personal preference than anything, so I just leave it up to you to resolve in the most appropriate way.
