### ISSUE TITLE
Spinner only works in RStudio and RGui, but not Rterm (on Windows)

### ISSUE THREAD

**Issue by datafj** [r-lib/cli#243]
This is my observation of running demo_spinners() on Windows desktop:

- Works perfectly in RStudio. 
- Can display characters correctly in RGui, but the animation does not work. It seems the R console in RGui does not refresh itself properly.
- In Rterm (run r.exe from cmd), the spinner characters are shown as "<U+xxxx>".

I first thought the Rterm problem is because Windows Command Line console couldn't show Unicode. But then I ran the Windows cmd inside ConEmu and ran the Unicode and UTF-8 tests provided at the bottom of https://conemu.github.io/en/UnicodeSupport.html , it turned out the Windows cmd had no problem displaying Unicode characters. However, ran cli::demo_spinners() still only got "<U+xxxx>".

**Comment by gaborcsardi** [comment]
The animation should work, but one needs to either turn off the output buffering (CTRL+W afair), or you need to call `flush.console()` after each update. `demo_spinners()` could do that.

The `"<U+xxxx>"` text is coming from R and there is no way around it. You cannot use Unicode characters in RTerm.

**Comment by datafj** [comment]
This blog post from the R project may be relevant: [UTF-8 Support on Windows](https://developer.r-project.org/Blog/public/2020/05/02/utf-8-support-on-windows/)

As they suggested, I typed “chcp 65001” in Windows cmd before I enter Rterm. It did make their Unicode example work, but demo_spinners() still gives me  "<U+xxxx>".

The blog post also mentioned all packages need to recompile with Universal C Runtime (UCRT) to make it work.
