### ISSUE TITLE
Multi-byte text garbled on Windows

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#267]
I'm working on getting googledrive to not garble a to-be-uploaded filename that contains multibyte text. I've done that (at least, for one way of specifying the file).

But now I notice such Drive filenames are garbled when printed via `cli::cli_bullets()`.

I can't use `reprex()` because of weird interactions with Windows and encoding and knitr, so here's a transcript of what I see in the Console (Windows 10, R 4.0.5):

``` r
> x <- drive_upload(
+   csv_filepath,
+   "Title with multibyte - マルチバイトのタイトル",
+   type = "spreadsheet",
+   overwrite = TRUE
+ )
Local file:
* C:/Users/jenny/Desktop/googledrive/inst/extdata/chicken.csv
Uploaded into Drive file:
* Title with multibyte - <U+30DE><U+30EB><U+30C1><U+30D0><U+30A4><U+30C8><U+306E><U+30BF><U+30A4><U+30C8><U+30EB>
  <id: 1EnfDPQ_Ovss2NC6l-h7V_GKSVgYG8_bYfeHi7_gwAm8>
With MIME type:
* application/vnd.google-apps.spreadsheet
> x$name
[1] "Title with multibyte - マルチバイトのタイトル"
```

Notice that the file's name prints correctly via `x$name`.

A reprex that has nothing to do with googledrive:

```
> x <- "Text with multibyte - マルチバイトのタイトル"
> x
[1] "Text with multibyte - マルチバイトのタイトル"
> cli::cli_alert(x)
> Text with multibyte - <U+30DE><U+30EB><U+30C1><U+30D0><U+30A4><U+30C8><U+306E><U+30BF><U+30A4><U+30C8><U+30EB>
```

**Comment by gaborcsardi** [comment]
Yeah, I guess we call `format()` at some point, which re-encodes into the native encoding...

**Comment by gaborcsardi** [comment]
So, this now works well, except in errors and warnings, which we cannot fix because of base R converting error messages to the native encoding:

```r
> s1 <- "\u30DE\u30EB\u30C1\u30D0\u30A4\u30C8\u306E\u30BF\u30A4\u30C8\u30EB"
> cli_text(s1)
マルチバイトのタイトル
```

```r
> cli_abort(s1)
 Error: <U+30DE><U+30EB><U+30C1><U+30D0><U+30A4><U+30C8><U+306E><U+30BF><U+30A4><U+30C8><U+30EB>
Run `rlang::last_error()` to see where the error occurred. 
[...]
```

```r
> rlang::last_error()
<error/rlang_error>
マルチバイトのタイトル
Backtrace:
 1. cli::cli_abort(s1)
Run `rlang::last_trace()` to see the full context.
```
