### ISSUE TITLE
LaTeX compatibility

### ISSUE THREAD

**Issue by krlmlr** [r-lib/cli#27]
Many symbols do not render properly in a LaTeX document: [LaTeX.pdf](https://github.com/r-lib/cli/files/1436914/LaTeX.pdf). What's the best way to deal with this?

We can detect if LaTeX output is active, https://github.com/r-lib/pillar/issues/61#issuecomment-341296361:

> `knitr:::is_latex_output()`. This function was exported recently in the devel version of knitr.

Should we work along these lines? Or should knitr (or even the user) just set the `cli.unicode` option?

**Comment by gaborcsardi** [comment]
One good way would be to use a modern unicode alternative like xetex. I am not sure if this is easy with knitr or not. 

Yes, the other way would be to set `cli/unicode` to `FALSE`.

**Comment by krlmlr** [comment]
The PDF has been produces with xetex; plain pdflatex will give errors.

It feels easiest to query for LaTeX output here than the other way round. Example: r-lib/pillar@170deca9.

**Comment by gaborcsardi** [comment]
@krlmlr so we should do this in `cli` as well?

**Comment by krlmlr** [comment]
That's what I'd suggest. Eventually pillar will use cli.
