### ISSUE TITLE
Add inline class for a column name

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#270]
In my recent cli adventures, it feels like we might be missing an inline class for column names. I believe this should probably be an alias for `.code`. But spelling this out has various advantages (makes a policy obvious / tweakable, more readable code, etc.) and I imagine this is easy to implement.

**Comment by gaborcsardi** [comment]
`{.col}` ?

**Comment by jennybc** [comment]
Yeah I agree `.col` is the way to go, all things considered.

**Comment by gaborcsardi** [comment]
Can't we (re)use `{.var}`?

**Comment by jennybc** [comment]
Are you saying that `.var` and `.col` and `.code` should all (probably) get the same styling?

Or are you suggesting that we not create `.col` and, instead, mark column names up with `.var`?

I feel like the justification for having both `.col` and `.var` is similar to having both `.file` and `.path`.

**Comment by gaborcsardi** [comment]
> Or are you suggesting that we not create .col and, instead, mark column names up with .var?

Yeah. In the tidy data sense a column name is a variable name, and the formatting would be probably very similar.

**Comment by jennybc** [comment]
Yes it's easier to imagine `.code` not being exactly the same as `.var` and `.col`. Or, at least, you could imagine some context where someone had a legit reason to want this.

I think `.var` and `.col` would probably always be styled the same? But `.col` seems like such an important special case that it's reasonable for it to exist. But I can also live without it!

**Comment by gaborcsardi** [comment]
Yeah, the pro of having both is that your code can be potentially more readable. The con is that if you style them, you need to remember to style both. Like if you style `.file`, you'd probably want to style `.path` the same way.

**Comment by jennybc** [comment]
Can you implement using the class-map feature so `(.file,.path)` and `(.var, .col)` are internally consistent, by definition?
