### ISSUE TITLE
Parameterise collapsing inline

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#277]
By default cli collapses with "and":

```r
cli::cli_text("{.arg {c('foo', 'bar')}}")
#> `foo` and `bar`
```

I'm not sure how to change the collapsing while still applying a particular span syntax. Would it be possible to find an inline syntax to select a collapsing style?

**Comment by gaborcsardi** [comment]
Collapsing also happens without inline styling, and currently you can specify the style on the vector itself, with `cli_vec()`. E.g.

```r
v <- cli_vec(letters[1:5], list(vec_last = " or "))
cli_text("{v}")
#> a, b, c, d or e
```

Is this good?

**Comment by lionel-** [comment]
Thanks, it's nice to have a working solution. It feels like it needs something more user friendly for such a common operation, maybe a `cli_or()` wrapper? Feel free to close though.
