### ISSUE TITLE
Named first elements

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#282]
Should only unnamed first elements be given "1" as default name? Then this would produce two bullets:

```r
cat(cli::format_error(c("*" = "foo", "*" = "bar")), "\n")
#> foo
#> • bar 
```

**Comment by gaborcsardi** [comment]
We can do this, but I don't suggest using it for errors, as the bullets will not line up, because of the added `Error:` prefix:

```r
❯ stop(cli::format_error(c("*" = "foo", "*" = "bar")))
Error: • foo
• bar
```

**Comment by lionel-** [comment]
Right, that would be used for formatting a list of bullets to which an error header is later appended. Thanks!
