### ISSUE TITLE
Header, body, and footer variants of `format_error()`, `format_warning()`, and `format_message()`

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#283]
To be called from `cnd_header()`, `cnd_body()`, and `cnd_footer()` methods. This will be needed to switch vctrs to cli.

The warning and message variants are not needed right away since the three-parts generics are not implemented yet for these (but planned in https://github.com/r-lib/rlang/issues/1070).

Issues from formatting separately:

- Extra ANSI sequences for closing and opening formats. This could be a problem with the character limit for errors.
- Performance of cli formatting. However these methods are called lazily so shouldn't be an issue in normal code. This will however make testing of errors with testthat even slower.

**Comment by lionel-** [comment]
Or should we just use this pattern (the bullet formatting will require #282):

```r
cli::format_error("Header")

cli::format_error(c("i" = "Bullet"))
```

This would avoid making the cli API too complex with many variants. We just need to add footer syntax, maybe `"_"` or `"..."`?

```r
cli::format_error(c(
  "Header",
  "i" = "Bullet",
  "_" = "Footer"
))
```

And footers would be styled the same way the rlang `last_error()` reminder is?

**Comment by lionel-** [comment]
What do you think of the last idea @gaborcsardi? I think this would be much preferable to having many variants. You'd have to add variants for warnings and messages to be complete, and that becomes a bit much.

**Comment by gaborcsardi** [comment]
That already works, you can use `"1"` for the header, and `"_"` for the footer, although the latter is not styled at all currently.

**Comment by lionel-** [comment]
So maybe we should try that out before adding 3 functions to the API? I could try it out in vctrs when I switch it to cli.

**Comment by gaborcsardi** [comment]
OK, I can remove them then. 

I am not sure how the footer should be styled, btw. Currently it is not styled at all, because rlang styles it manually.

**Comment by lionel-** [comment]
yup it's probably fine to keep the footer unstyled.

**Comment by gaborcsardi** [comment]
OK, I'll close this now then.
