### ISSUE TITLE
"i" at the front of cli messages

### ISSUE THREAD

**Issue by juniperlsimonis** [r-lib/cli#287]
upon a recent update to cli_2.5.0, I started getting `i ` at the front of messages in `devtools` (on two different windows machines, build info for one below). I haven't been able to track it down completely, as I'm new to the package (I only came to it because of noticing the issue in devtools), but I've made some headway.

```
> devtools::load_all()
i Loading PackageName
```

I can recreate the output when just using `cli` directly:

```
> cli::cli_alert_info("message")
i message
```

It looks like its added onto the message in `clii_alert`, as it appears there even when passed a simple list message

```
> cli:::clii_alert(cli:::default_app(), "alert-info", list(str = "message"), id = NULL, class = NULL, wrap = FALSE)
i message
```

The default app inline function does not add it

```
> cli:::default_app()$inline(list(str = "message"))
[1] "message"
```

Nor does the before and after pasting

```
> text <- cli:::default_app()$inline(list(str = "message"))
> before <- cli:::call_if_fun(cli:::default_app()$get_current_style()$before) %||% ""
> after <- cli:::call_if_fun(cli:::default_app()$get_current_style()$after) %||% ""
> 
>         before <- gsub(" ", " ", before)
>         after <- gsub(" ", " ", after)
>         text[1] <- paste0(before, text
+ [1])
> paste0(text[length(text)], after)
[1] "message"
```

This is as far as I've gotten so far in pin pointing where it's coming from

```
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)
```

**Comment by gaborcsardi** [comment]
This is how informational alerts are formatted in cli. I don't think this is recent, it was always like this, since cli had the `cli_alert_*` functions:

```r
❯ { cli_alert_info("info"); cli_alert_success("success"); cli_alert_warning("warning"); cli_alert_danger("danger") }
ℹ info
✔ success
! warning
✖ danger
```

**Comment by juniperlsimonis** [comment]
oh! gotcha.
this just started today after an update to packages that couldn't have been more than a month or so old
perhaps they were masked in devtools at that level before and they are no longer?
is there a way to silence that additional formatting? 
thanks for the info.

**Comment by gaborcsardi** [comment]
> is there a way to silence that additional formatting?

```r
options(cli.user_theme = list(".alert" = list(before = NULL)))
```

**Comment by juniperlsimonis** [comment]
awesome, thank you so much!  i appreciate it!
