### ISSUE TITLE
Alternative to stop message

### ISSUE THREAD

**Issue by markwsac** [r-lib/cli#291]
Thanks for this lovely package. Just wanted to know if there is any function which is an alternative to `stop( )` which kills the task at hand and shows error message. My idea is to style error message and halts the execution.

**Comment by gaborcsardi** [comment]
There is now a `cli_abort()` function, which calls rlang, and can use cli's semantic UI:

```r
bad <- 10
cli::cli_abort("Failed to {.emph download} {bad} package{?s}")
```

<img width="659" alt="Screen Shot 2021-06-26 at 18 26 33" src="https://user-images.githubusercontent.com/660288/123519534-25b0e100-d6ac-11eb-9c77-96b1bed603f4.png">


Or you can use `format_error()` with `stop()` if you don't want to call rlang:

```r
bad <- 10
stop(cli::format_error("Failed to {.emph download} {bad} package{?s}"))
```

<img width="660" alt="Screen Shot 2021-06-26 at 18 26 53" src="https://user-images.githubusercontent.com/660288/123519535-2b0e2b80-d6ac-11eb-844d-832c59d2e0e1.png">
