### ISSUE TITLE
Some Homepage Issues

### ISSUE THREAD

**Issue by mgirlich** [r-lib/cli#302]
The [article link](https://cli.r-lib.org/articles/) in the news shows a list of articles and found some small issues:

* Two _UNKNOWN TITLE_ articles (missing in menu)
* The order is different from the menu point _Articles_
* _CLI pluralization_ vs _cli pluralization_
* _cli progress bar benchmark_ missing in menu

![image](https://user-images.githubusercontent.com/18258854/124074969-7fb2fd00-da44-11eb-9d66-79c71f7c59f2.png)

The [benchmarks](https://cli.r-lib.org/articles/progress-benchmark.html) are not very readable

![image](https://user-images.githubusercontent.com/18258854/124075470-2dbea700-da45-11eb-9c53-8a2142b93d18.png)

The function `ticking()` is exported but doesn't really seem to be documented.

Pretty nice work with the progress bars! 😄

**Comment by gaborcsardi** [comment]
Thanks! Some of these vignettes are internal. I updated the menu.

`ticking()` being non-documented is intentional, because we haven't decided about it yet. Do not use it.
