### ISSUE TITLE
Better  CLI_TICK_TIME defaults for dynamic terminals?

### ISSUE THREAD

**Issue by tzakharko** [r-lib/cli#304]
Animation update timer in as of version `3.0.0` defaults  to use 200ms in interactive sessions and 3s in non-interactive sessions. The tools I am developing are non-interactive, but they are primarily run in a dynamic terminal, where these defaults result in laggy animations. It is possible to modify the default via the `CLI_TICK_TIME` environmental variable, but that's not the most convenient way of doing things. This variable has to be set before `cli` is loaded, which makes using it awkward. For example, one can't  use `is_dynamic_tty()` to check if the terminal is dynamic (as that would load the package and use the default values). Or, if a user has an `.Rprofile` that loads `cli` on startup, manipulating the variable at the beginning of my script won't have any effect. And setting `CLI_TICK_TIME` in the shell creates issues with user experience. 

Since it seems that dynamic discovery of timer interval would be too complicated, may I suggest that the shorter update interval is chosen for interactive **and** dynamic sessions? This would solve all the current problems with animations in rich terminals. The change would be trivial:

https://github.com/r-lib/cli/blob/08695e486eb5630eb350086f0eb905223ffcf7e6/R/onload.R#L44

```diff
-    tt <- if (interactive()) {
+    tt <- if (interactive() || is_dynamic_tty() ) {
```

**Comment by gaborcsardi** [comment]
Yeah, that would probably make sense. Do you want to submit a PR?

**Comment by tzakharko** [comment]
PR submitted, I also took the liberty to tweaking the documentation where these things are mentioned (I might have missed a thing  or another). Please tell me if there is something missing.
