### ISSUE TITLE
`ansi_strtrim()` falls over if there's an `NA`

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#309]
It feels like an `NA` should just propagate here. I encountered this while implementing a format method (well, technically, a `pillar_shaft()` method).

``` r
x <- month.name
cli::ansi_strtrim(x, width = 3)
#> <ansi_string>
#> [1] Ja… 
#> [2] Fe… 
#> [3] Ma… 
#> [4] Ap… 
#> [5] Ma  
#> [6] Ju… 
#> [7] Ju… 
#> [8] Au… 
#> [9] Se… 
#> [10] Oc…
#> [11] No…
#> [12] De…

x[2] <- NA
cli::ansi_strtrim(x, width = 3)
#> Error in ansi_substr(xt[bad], 1, ansi_nchar(xt[bad]) - 1L): non-numeric substring arguments not supported
```

<sup>Created on 2021-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by gaborcsardi** [comment]
Closed in 910f92d4073d0a360d77a4351060f1970aa5d8f5
