### ISSUE TITLE
Using `cli_progress_bar()` in parallel

### ISSUE THREAD

**Issue by ms609** [r-lib/cli#322]
Is it possible (in principle or in practice) to use cli progress bars with parallel computation?

I'd like to be able to write:

```r
library("parallel")
env <- environment()
cli_progress_bar("Example", total = 10, .envir = env)
cl <- makeCluster(2)
parLapply(cl, 1:10, function (i, env) {
  Sys.sleep(1)
  cli::cli_progress_update(1,  .envir = env)
}, env)
stopCluster(cl)
```

but I see
` Cannot find current progress bar for <environment: R_GlobalEnv>`

Is the parent environment accessible to workers?  Or am I doing something silly?

**Comment by gaborcsardi** [comment]
No, not easily. You cannot just refer to an environment in another R process.

**Comment by ms609** [comment]
Thanks.  I wonder whether there are any alternatives, even if less elegant, that would reassure the user that something is happening?

**Comment by gaborcsardi** [comment]
This thread and the links within are probably of interest for you: https://stat.ethz.ch/pipermail/r-package-devel/2021q3/007216.html
