### ISSUE TITLE
cat_line() etc don't respect width

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#33]
```R
withr::with_options(list(width = 20), cli::cat_rule())
#> ──────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by gaborcsardi** [comment]
Only in RStudio, because the env var takes precedence there. This works everywhere: 
```r
withr::with_options(list(cli.width = 20), cli::cat_rule())
```

**Comment by hadley** [comment]
Hmmmm, I thought the env var was only set in the build pane environment.

**Comment by gaborcsardi** [comment]
I am closing this, as I don't see how we could improve the behavior, without modifying the env vars set by RStudio. Please reopen if you want to change the current behavior.
