### ISSUE TITLE
Feature request: Add emoji support

### ISSUE THREAD

**Issue by danielvartan** [r-lib/cli#330]
It would be nice if `cli` supported emojis. It would make the command line interface more attractive and fun!

This could be integrated by importing the `emojifont` package.

**Comment by gaborcsardi** [comment]
cli does support emoji already, e.g.

```r
x <- "\U0001f477\U0001f3fc\u200d\u2642\ufe0f"
cli::ansi_nchar(x)
#> [1] 1

cat(x)
#> 👷🏼‍♂️
```

I don't know the emojifont package, but it seems to me that it is about having emojis in graphics and not at the console.
