### ISSUE TITLE
Wrong link in https://cli.r-lib.org/reference/cli_progress_bar.html

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/cli#331]
In the second sentence of https://cli.r-lib.org/reference/cli_progress_bar.html there's a link  supposedly pointing to *cli progress bars*. 

It's not.

It's pointing to *cli pluralization*, i.e.: https://cli.r-lib.org/articles/pluralization.html.

**Comment by assignUser** [comment]
This was fixed in #340 :)

**Comment by gaborcsardi** [comment]
Indeed, thanks!
