### ISSUE TITLE
Black svg rectangle in https://cli.r-lib.org/articles/progress-advanced.html

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/cli#332]
In https://cli.r-lib.org/articles/progress-advanced.html there is this black rectangle... probably not intended, right?

![snap](https://user-images.githubusercontent.com/19862384/128617306-110b66ed-f22b-41c3-9efc-3ffc4ea67cd6.png)

**Comment by gaborcsardi** [comment]
Thanks, fixed!

**Comment by ramiromagno** [comment]
The problem seems to persist.

**Comment by gaborcsardi** [comment]
It is fixed on the dev site: https://cli.r-lib.org/dev/articles/progress-advanced.html  
The manual of the released version will be updated after the next release.

**Comment by ramiromagno** [comment]
Cheers @gaborcsardi !
