### ISSUE TITLE
Apostrophe (and maybe other characters) in process messages result in no output

### ISSUE THREAD

**Issue by mrcaseb** [r-lib/cli#333]
The `cli_process_*` messages are not printed to the console if the message includes an apostrophe. I didn't test for other characters so I am not sure if it's the only one.  

``` r
library(cli)

test_process_message <- function(failed_message){
  cli_process_start(msg = "Do something ")
  Sys.sleep(1)
  cli_process_failed(msg_failed = failed_message)
}

test_process_message("this doesn't work")
#> i Do something                
test_process_message("this does not work")
#> i Do something x this does not work
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I am quite sure it happens in these lines
https://github.com/r-lib/cli/blob/457ad4403ae7cd062c1e11fb99b9b48013b58c9b/R/status-bar.R#L234
https://github.com/r-lib/cli/blob/457ad4403ae7cd062c1e11fb99b9b48013b58c9b/R/status-bar.R#L237
https://github.com/r-lib/cli/blob/457ad4403ae7cd062c1e11fb99b9b48013b58c9b/R/status-bar.R#L240
https://github.com/r-lib/cli/blob/457ad4403ae7cd062c1e11fb99b9b48013b58c9b/R/status-bar.R#L260
https://github.com/r-lib/cli/blob/457ad4403ae7cd062c1e11fb99b9b48013b58c9b/R/status-bar.R#L273

where the message is formatted using message classes and the apostrophe messes up the message.

**Comment by gaborcsardi** [comment]
This is from glue, and I don't really understand why it is happening:

```r
❯ str(glue::glue("{this doesn't work}"))
 'glue' chr ""
❯ str(glue::glue("{this does not work}"))
Error in parse(text = text, keep.source = FALSE) :
  <text>:1:6: unexpected symbol
1: this does
```

**Comment by mrcaseb** [comment]
> 
> 
> This is from glue, and I don't really understand why it is happening:
> 
> ```r
> ❯ str(glue::glue("{this doesn't work}"))
>  'glue' chr ""
> ❯ str(glue::glue("{this does not work}"))
> Error in parse(text = text, keep.source = FALSE) :
>   <text>:1:6: unexpected symbol
> 1: this does
> ```

I think the problem was that the string inside `{}` wasn't a string at all. 

And maybe escaping the apostrophe helps?

``` r
str(glue::glue("{'this doesn't work'}"))
#>  'glue' chr ""
str(glue::glue("{'this does not work'}"))
#>  'glue' chr "this does not work"
str(glue::glue("{'this doesn\\'t work'}"))
#>  'glue' chr "this doesn't work"
```

<sup>Created on 2021-08-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mrcaseb** [comment]
I should add that I tested escaping the apostrophe for the `cli_process_*` messages and it didn't help

**Comment by gaborcsardi** [comment]
This is now fixed in dev glue at https://github.com/tidyverse/glue/pull/226, so I am closing this.
