### ISSUE TITLE
Integer overflow when using the C progress bar API

### ISSUE THREAD

**Issue by jimhester** [r-lib/cli#335]
When using the C progress bar API it is possible to overflow the 32 bit `int` data type if you pass a value larger than can be stored in an `int`, e.g. more than 2147483647.

In my case I was trying to use the `download` progress bar type and simply passing the number of bytes read so far to `cli_progress_set()` with a ~ 3 Gb file.

Would it be possible for the functions accept a wider integer type like `int64_t` or `size_t` to avoid this issue for most real world integers?

**Comment by jimhester** [comment]
I know I could specify a custom format to work around this, but then I would have to recreate the current and total byte calculations etc.

**Comment by gaborcsardi** [comment]
Yeah, we can use a different type in the C code, the question is what type to use in the R code.

**Comment by gaborcsardi** [comment]
I guess we could use a double, but then for large 64 bit integers it will be inaccurate. Is that OK?

**Comment by jimhester** [comment]
Yeah I think using double is OK, 2^53 is pretty big

**Comment by gaborcsardi** [comment]
OK. This is a breaking change, but hopefully no packages use the C API yet. (We should probably version the API and embed the version in the binary packages that use cli.)
