### ISSUE TITLE
Should error messages be formatted in plain text instead of bold?

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#339]
`format_error()` currently makes the error message bold. This looks good with a list of bullets:

<img width="648" alt="Screenshot 2021-09-01 at 11 34 27" src="https://user-images.githubusercontent.com/4465050/131648575-81dc9813-039f-4079-95e2-8af7f6494612.png">

However this doesn't work so well in case of chained errors:

<img width="439" alt="Screenshot 2021-09-01 at 11 35 47" src="https://user-images.githubusercontent.com/4465050/131648766-8cfebe01-4b17-44d1-a70e-ec000b6bb2d4.png">

This looks better:

<img width="293" alt="Screen Shot 2021-08-31 at 1 57 47 PM" src="https://user-images.githubusercontent.com/4465050/131648834-f16f61fe-41f0-43fb-a42d-a24bdc30642d.png">

cc @hadley @DavisVaughan

**Comment by hadley** [comment]
Yeah, I think the "error" and "caused by" should be in bold, but nothing else. 

cc @jennybc

**Comment by gaborcsardi** [comment]
Reprex:

```r
cli::format_error(c("This is a message.", i = "This is a bullet.", i = "Another bullet."))
#> [1] "\033[1m\033[22m\033[1m\033[1mThis is a message.\033[1m\033[22m\n\033[36mℹ\033[39m This is a bullet.\n\033[36mℹ\033[39m Another bullet."
```
