### ISSUE TITLE
Consider special case for latex environments?

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#34]
https://community.rstudio.com/t/tidyverse-1-2-1-knitting-to-pdf-issue/2880

I think we can detect this (at least for knitr) by inspecting options.

**Comment by gaborcsardi** [comment]
Yeah, so even the non-UTF8 symbols break latex, in particular the tick marks. So we either need to have a third set of symbols, for latex, or dumb down the windows symbols to 7 bit ASCII only.
