### ISSUE TITLE
Let `format_error()` (and variants?) know about starting column

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#345]
With dev rlang the starting column is not fixed because the message is no longer always displayed after "Error: ", it could be "Error in `foo()`: or it could be starting at column 2 (or column 0 + indent 2 more precisely?) in case of chained errors. Could we have a way of specifying the starting column?

**Comment by gaborcsardi** [comment]
@lionel- do you still need this?

**Comment by lionel-** [comment]
I no longer need this, see https://github.com/r-lib/cli/pull/364#issuecomment-1016346807
