### ISSUE TITLE
cli_dl() is broken?

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#347]
``` r
packageVersion("cli")
#> [1] '3.0.1'
cli::cli_dl("abc")
#> Error in eval(expr, envir = envir): object '.dt' not found
```

<sup>Created on 2021-09-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by gaborcsardi** [comment]
The error message is not great indeed, but you need a named character vector:
```r
❯ cli::cli_dl(c(xyz = "abc"))
xyz: abc
```

**Comment by hadley** [comment]
Oh, my actual problem was slightly different:

``` r
cli::cli_dl(c("abc" = ""))
#> Error in eval(expr, envir = envir): object '.dd' not found
```

<sup>Created on 2021-09-09 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by gaborcsardi** [comment]
Yeah, with zero length strings it does not work, that's a real bug. You can use a space as a workaround:
```r
❯ cli::cli_dl(c("abc" = " "))
abc:
```
