### ISSUE TITLE
Unexpected indenting or truncation of messages

### ISSUE THREAD

**Issue by lazappi** [r-lib/cli#352]
I have noticed that some of my messages are unexpectedly indented or truncated. I have found it hard to reproduce so possibly it is something specific to my setup (RStudio on MacOS). It's also possible I'm just doing something incorrectly, just let me know if that's the case.

Here are the conditions that seem to reproduce for me:

1. Call `cli_process_start()` with a relatively long message
2. Call `cli_progress_step()` with a field in the message
3. Call one of the `cli_alert()` functions

``` r
f <- function() {
    cli::cli_process_start(
        "A main process with a long message saying what it is doing"
    )
    cli::cli_progress_step("Some intermediate step with a {.field field}")
    cli::cli_alert_warning("An alert messsage which is long enough")
}
f()
#> ℹ A main process with a long message saying what it is doing
#> ℹ Some intermediate step with a field
#> ! An alert messsage which is long enough
#> ℹ Some intermediate step with a field✓ Some intermediate step with a field [19ms]
#> 
#> ℹ A main process with a long message saying what it is doing✓ A main process with a long message saying what it is doing ... done
```

<sup>Created on 2021-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It doesn't seem to happen in the reprex which is annoying but what I see is the `cli_progress_step()` message is indented. Sometimes instead of this happening the `cli_alert()` message is truncated which I think is probably a worse effect.

<img width="690" alt="Screen Shot 2021-09-14 at 16 56 53" src="https://user-images.githubusercontent.com/6869320/133281748-68338b45-ab3c-42a5-a5ab-2c5bd64a7d89.png">

I realise this is probably a weird edge case so totally understand if you don't want to spend time on it but thought I would open an issue in case it comes up for anyone else.

**Comment by gaborcsardi** [comment]
I can't reproduce this with cli from CRAN or GH. What is your platform, and the output of `sessioninfo::session_info()`?

**Comment by gaborcsardi** [comment]
Actually, scratch that, I can reproduce it in RStudio, with both the CRAN and GH version of cli.

**Comment by gaborcsardi** [comment]
Unfortunately this seems like a bug in RStudio, because it looks good in the terminal.

```r
msg <- c( 
"\r\033[36mℹ\033[39m Some intermediate step with a \033[32m\033[32mfield\033[32m\033[39m                       \r", 
"\r                                     \r", "\033[33m!\033[39m An alert messsage which is long enough\n", 
"\033[36mℹ\033[39m Some intermediate step with a \033[32m\033[32mfield\033[32m\033[39m\r")
cat(msg, sep = "")
```

```
! An alert messsage which is long enough
                       ℹ Some intermediate step with a field
```

**Comment by gaborcsardi** [comment]
A simpler reprex. If I drop a space from the second element that fixes it, probably some edge case.

```r
msg <- c( 
  "ℹ Some intermediate step with a \033[32mfield\033[39m                       ", 
  "\r                                     \r", 
  "\033[33m!\033[39m An alert message which is long enough\n", 
  "ℹ Some intermediate step with a \033[32mfield\033[39m\n"
)
cat(msg, sep = "")
```

**Comment by gaborcsardi** [comment]
Reported as an Rstudio bug. Maybe we can work around it, I don't quite yet get what the bug is.

**Comment by gaborcsardi** [comment]
Seems like an easy workaround is to add an extra space for the "erasing string":

```r
msg <- c( 
  "ℹ Some intermediate step with a \033[32mfield\033[39m                       ", 
  "\r                                      \r", 
  "\033[33m!\033[39m An alert message which is long enough\n", 
  "ℹ Some intermediate step with a \033[32mfield\033[39m\n"
)
cat(msg, sep = "")
```

I will have to check if a similar modification fixes the original reprex as well.

**Comment by gaborcsardi** [comment]
Indeed the workaround seems to work. Please reopen this or open another issue if you still have problems. Thanks!
