### ISSUE TITLE
RStudio jobs pane not detected

### ISSUE THREAD

**Issue by tentacles-from-outer-space** [r-lib/cli#353]
`cli` does not detect support in RStudio jobs output pane.

The following script

```{r}
message("Default configuration:\n\n")

cli::cli_alert_danger("cli::cli_alert_danger")
cli::cli_alert_success("cli::cli_alert_succes")
message(cli::bg_green("cli::bg_green()"))
crayon::show_ansi_colors()

message("\n\nAnd now forcing colors:\n\n")

options(cli.num_colors=256L)

cli::cli_alert_danger("cli::cli_alert_danger")
cli::cli_alert_success("cli::cli_alert_succes")
message(cli::bg_green("cli::bg_green()"))
crayon::show_ansi_colors()
```

gives output:

![image](https://user-images.githubusercontent.com/1562600/133457976-fec367f0-b90d-468f-af1d-bf3809f338de.png)

**Comment by gaborcsardi** [comment]
Do you know if it is possible to detect 1) that we are in the job pane, and 2) that the shell has color support?

**Comment by tentacles-from-outer-space** [comment]
First of all I see it is also a problem in crayon: https://github.com/r-lib/crayon/issues/121 (and more discussion on related RStudio issue).

ad1) I don't think it is possible, but, for example, `Sys.getenv("RSTUDIO")` returns `1`
ad2) `Sys.getenv("RSTUDIO_CONSOLE_COLOR")` in a job returns 256

**Comment by gaborcsardi** [comment]
> First of all I see it is also a problem in crayon: r-lib/crayon#121 (and more discussion on related RStudio issue).

The detection code is the same in both packages.

> ad1) I don't think it is possible, but, for example, Sys.getenv("RSTUDIO") returns 1
> ad2) Sys.getenv("RSTUDIO_CONSOLE_COLOR") in a job returns 256

Yes, because environment variables are inherited in child processes. But ANSI colors are usually not supported in child processes.

**Comment by gaborcsardi** [comment]
Seems like some environment variables are only set in RStudio jobs, e.g.
```
RSTUDIOAPI_IPC_REQUESTS_FILE
                        /var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpiFtqGM/rstudio-ipc-requests-da54488bf181.rds
RSTUDIOAPI_IPC_RESPONSE_FILE
                        /var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/RtmpiFtqGM/rstudio-ipc-response-da545b9c715c.rds
RSTUDIOAPI_IPC_SHARED_SECRET
                        9d2124ca-988a-4b30-8d2a-3e6a81ce8dc7
```

So we can use these to turn on colors, together with `RSTUDIO_CONSOLE_COLOR`.
