### ISSUE TITLE
Autodetect if Rmd is rendered via `@includeRmd`

### ISSUE THREAD

**Issue by dfalbel** [r-lib/cli#361]
I wonder if cli could autodetect if the Rmd is running through an `@includeRmd` tag and thus being included in an `. Rd` file and in this case set `cli.unicode=FALSE`. 

Otherwise, the Rmd can end-up rendering unicode characters in the .Rd and generate issues when building the PDF manual:

```
LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
! Package inputenc Error: Unicode char ─ (U+2500)
(inputenc)                not set up for use with LaTeX.
```

For example: 

https://github.com/mlverse/luz/blob/f8a34dcc815651456ece210dcdcd60b4e97ebc8d/man/evaluate.Rd#L63

**Comment by gaborcsardi** [comment]
Yeah, this is annoying. There is currently no official way to detect roxygen2, so we would need to address this there first.

This is also related: https://github.com/r-lib/roxygen2/issues/1240

Ideally, we would have Unicode in the HTML help and in pkgdown, and would only turn it off in the PDF manual.

For now, a workaround is to turn it off before the `@includeRmd`:

```r
#' Test
#'
#' `r options(cli.unicode = FALSE)`
#'
#' @includeRmd test.Rmd
#' @name test
NULL
```

This of course turns it off for the whole session, but if you run `document()` is a subprocess or from the shell, then it is not too bad.

**Comment by gaborcsardi** [comment]
We actually still need support from roxygen2 for this.

**Comment by hadley** [comment]
Now part of https://github.com/r-lib/roxygen2/issues/1349
