### ISSUE TITLE
Number of colors with active sink

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#366]
https://github.com/r-lib/crayon/issues/120 also affects cli, not very surprisingly.

**Comment by DavorJ** [comment]
If one uses `sink()` to **split** the stream, then there are two or more connections (of which one is usually a file that doesn't support ANSI sequences). In that case the `cli::num_ansi_colors` defaults to 1, ignoring all ANSI sequences supported by the terminal. In such case the user should probably choose the behavior with `R_CLI_NUM_COLORS`, but it is not documented. Hence the following suggestion:

`?cli::num_ansi_colors` mentions: "If you want to _turn off_ ANSI colors, set the `NO_COLOR` environment variable to a non-empty value." 

I would add there: "On the other hand, if you want to enforce a specific number of ANSI colors, set the `R_CLI_NUM_COLORS` environment variable."
