### ISSUE TITLE
Generic style-able components

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#37]
### Intro

In addition to just status display, as in #24.

### Block elements

- [x] Headers, at least three levels: `h1`, `h2`, `h3`, etc.
- [x] Text
- [x] Verbatim text
- [ ] Markdown text
- [x] Paragraph: `par`
- [ ] Block quote: `blockquote`
- [x] Bulleted list: `ul`
- [x] Ordered list: `ol`
- [x] Definition list: `dl`
- [ ] Code block: `blockcode`
- [x] Alert (success, danger, warning, info): `alert`
- [ ] Progress bar: `progressbar`
- [ ] Table: `table`

### Inline elements. 

These can be used via embedded markup, see below.

- [x] inline code: `code`
- [x] emphasis: `emph`
- [x] strong emphasis: `strong`
- [x] package name: `pkg`
- [x] function name (maybe with package?): `func`
- [x] argument name: `arg`
- [x] keyboard keys: `key`
- [x] file: `file`
- [x] email: `email`
- [x] url: `url`
- [x] variable: `var`
- [x] environment variable: `envvar`

### Inline markup

Inline markup can be used via `glue`. E.g. 
```
"The {pkg processx} package..."
``` 
This is the same as 
```
"The {pkg(\"processx\")} package..."
``` 
but easier to read and write. If the package name is in a variable, then you can simply use 
```
"The {pkg(mypkg)} package..."
```

This syntax is not final. 

### Cross-package issues

One challenging part here is to have a well defined behavior when multiple packages use these components at the same time. E.g. the first package starts a paragraph, the second package issues an `alert`, etc.

**Comment by hadley** [comment]
Does `file` = `path`?

**Comment by gaborcsardi** [comment]
Yes, we can call it `path`, that's what most packages call it.

**Comment by gaborcsardi** [comment]
Mostly done. Will open separate issues for the rest.
