### ISSUE TITLE
cannot locate symbol "pthread_setcanceltype"

### ISSUE THREAD

**Issue by leechaowen** [r-lib/cli#372]
i have success compiled r-base version 4.1.2 in termux for my phone today. Some packages faild to install  which depend on  cli. Here show the detail log, how to fix it? Thanks. 

~ $ R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: aarch64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("cli")
trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/cli_3.1.0.tar.gz'
Content type 'application/octet-stream' length 482062 bytes (470 KB)
==================================================
downloaded 470 KB

* installing *source* package ‘cli’ ...
** package ‘cli’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c ansi.c -o ansi.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c cleancall.c -o cleancall.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c diff.c -o diff.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c errors.c -o errors.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c init.c -o init.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c md5.c -o md5.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c progress-altrep.c -o progress-altrep.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c progress.c -o progress.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c thread.c -o thread.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c tty.c -o tty.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c utf8.c -o utf8.o
gcc -I"/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/include" -DNDEBUG   -I/usr/local/include   -fpic  -g -O2  -c win-utf8.c -o win-utf8.o
gcc -shared -L/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/lib -L/usr/local/lib -o cli.so ansi.o cleancall.o diff.o errors.o init.o md5.o progress-altrep.o progress.o thread.o tty.o utf8.o win-utf8.o -L/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/lib -lR
installing to /data/data/com.termux/files/usr/local/R-4.1.2/lib/R/library/00LOCK-cli/00new/cli/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘cli’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/library/00LOCK-cli/00new/cli/libs/cli.so':
  dlopen failed: cannot locate symbol "pthread_setcanceltype" referenced by "/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/library/00LOCK-cli/00new/cli/libs/cli.so"...
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/data/data/com.termux/files/usr/local/R-4.1.2/lib/R/library/cli’

The downloaded source packages are in
        ‘/data/data/com.termux/files/usr/tmp/Rtmplvaytn/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("cli") :
  installation of package ‘cli’ had non-zero exit status

**Comment by gaborcsardi** [comment]
> i have success compiled r-base version 4.1.2 in termux for my phone today. Some packages faild to install which depend on cli. Here show the detail log, how to fix it? Thanks.

I am not sure what you mean, but that does not look like a successful installation. You need to create a `~/.R/Makevars` file like this: https://github.com/r-lib/cli/issues/358#issuecomment-932704906

**Comment by leechaowen** [comment]
Thanks. fix it now follow your way. Please close this issue.

~ $ mkdir .R
~ $ cd .R
~/.R $ ls -lrt
total 0
~/.R $ vim Makevars
~/.R $ pwd
/data/data/com.termux/files/home/.R
~/.R $ cat Makevars
PKG_LIBS+=-lbthread

**Comment by gaborcsardi** [comment]
> Please close this issue.

If you think your problem is solved, then you can also close it. :)
