### ISSUE TITLE
Lists inside bullets should be indented

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#378]
From @gaborcsardi :smile::

Nested lists are already indented in the default theme:

```
❯ l <- cli::cli_ul(); cli::cli_li("first"); cli::cli_ul(letters[1:3]); cli::cli_end(l)
• first
  • a
  • b
  • c
```

A `cli::cli_bullets()` is not an `ul` , but we can indent lists within the bullets as well.

**Comment by gaborcsardi** [comment]
Actually, can you even create a nested list inside bullets? `cli_bullets()` is a one-shot thing, it does not leave a container open that you can put lists into.

**Comment by lionel-** [comment]
I think we discussed at some point that this sort of things will have to wait until we can pass cli structures flexibly through `format_error()` and `cli_abort()`?
