### ISSUE TITLE
Helpers for error messages

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#38]
(Meta issue, will edit as I come across more small helpers):

```
dir_copy(c("foo", NA_character_, "bar", NA_character_), "blah")
#> Error: `path` must not have missing values
#> NAs found at 1,000,000 locations: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...
```

* Number formatting (e.g. set big mark)
* Commas + truncation
* Standard wrappers for argument names, paths, expressions

**Comment by jimhester** [comment]
https://github.com/r-lib/fs/commit/df2252aeadb44e66fc28d35ddd24dcad59f115bd is the code I am using in **fs** for this

**Comment by gaborcsardi** [comment]
Maybe #37 is relevant here, the inline markup part.

**Comment by gaborcsardi** [comment]
Should this be in cli at all? Shall we use glue for the formatting? I think we already have some of these functions in other packages, no? Where?

@hadley @jimhester

**Comment by hadley** [comment]
I think some of probably belong in cli — e.g. cli should provide standard colours + text formatting for when we put an argument name or a string in a message. But maybe you're thinking that should live in a higher level package where those settings can be controlled with a theme?

**Comment by gaborcsardi** [comment]
A common theme would be definitely nice. Theming is now in the cliapp package, but that's a bit too heavy as it is now, for a low-level infrastructure package, it needs xml2, selectr, progress. It is possible that we don't need hierarchical theming for CLI apps. OTOH it is _really_ nice to have it. We can work on thinning its dependencies.

**Comment by gaborcsardi** [comment]
OK, this will be proposed for after the coming 1.1.0 version, and I'll collect some use cases and mock up some API.
