### ISSUE TITLE
`style_hyperlink(params=)`

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/cli#384]
related to https://github.com/rstudio/rstudio/pull/10299

Can `style_hyperlink()` have a `params=NULL` that would target the `[params]` bit in the escape code https://iterm2.com/documentation-escape-codes.html

```
OSC 8 ; [params] ; [url] ST [text] OSC ] 8 ; ; ST
```

params then could be useful to control what kind of action is triggered by the link (open system browser, open help page, open something in viewer, navigate to file in the editor, ...).

**Comment by gaborcsardi** [comment]
Yes, definitely.

**Comment by romainfrancois** [comment]
Thanks. I added a pull request, nothing urgent as https://github.com/rstudio/rstudio/pull/10299 will probably need some time to mature. 

also wondering if `{.url` in `cli_text()` etc ... should make links with `style_hyperlink()`

**Comment by gaborcsardi** [comment]
> also wondering if {.url in cli_text() etc ... should make links with style_hyperlink()

Good idea: #386.
