### ISSUE TITLE
`.url` style should probably use `style_hyperlink()`

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#386]
Cf. https://github.com/r-lib/cli/issues/384#issuecomment-1006487134

**Comment by gaborcsardi** [comment]
It would be best to add hyperlink support to the `ansi_*()` functions as well.

**Comment by gaborcsardi** [comment]
I think we could think about this a bit more, so I'll skip it for now.

**Comment by hadley** [comment]
I think `.file` could also use `style_hyperlink()`.
