### ISSUE TITLE
Global option to disable unicode in condition bullets

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#396]
This option should only be inspected when `cli.unicode` is enabled. I.e. it's a way of opting out of unicode in condition message bullets when unicode is globally enabled, not opting in when it's globally disabled.

This way reproducible environments only need to disable `cli.unicode` without having to know about condition bullets. On the other hand, unit tests that specifically enable unicode will need to know about the bullets-specific option for reproducibility in sessions where the user has disabled unicode bullets, but that's a rare case.

I think the name should be nested in `cli.unicode_`, mention bullets, and mention that it's about condition messaging. One of these would be good:

- `cli.unicode_cnd_bullets`
- `cli.unicode_condition_bullets`
- `cli.unicode_message_bullets`

Or perhaps nest in `cli.unicode_bullets_` in case similar options are added for bullets in other contexts?

**Comment by gaborcsardi** [comment]
`cli.condition_unicode_bullets` it will be
