### ISSUE TITLE
question: c: Is this safe just to use index but not checking length?

### ISSUE THREAD

**Issue by zhiburt** [r-lib/cli#399]
Hi there,
An awesome library you made I think.

I am not a C expert and I haven't touched R at all yet so far.
But as I am aware of we when we don't check the length we might go over bounders of allocated memory in case if ptr argument built this way.
I consider that probably everything is OK with this but.
This approach is taken all the time so I just want to bring your attention.

https://github.com/r-lib/cli/blob/b1ea6657feaa2a368dd7a57663c887ffb679deb4/src/ansi.c#L161-L167

Thank your for the library.
Have a great 2022.

**Comment by gaborcsardi** [comment]
The input is a zero byte terminated string, so `(*ptr)[0]`, etc. will check that there are more bytes to process.
