### ISSUE TITLE
Use cli_ prefix for classes

### ISSUE THREAD

**Issue by krlmlr** [r-lib/cli#403]
This avoids clashes with other packages that may define the same class, e.g. RNeXML (https://github.com/ropensci/RNeXML/issues/251). AFAICT this affects the following classes:

- ansi_string
- ansi_style
- boxx
- rule
- tree

Would you review a PR?

**Comment by gaborcsardi** [comment]
This is quite painful, but yeah, I'll review a PR, thanks much. There'll be a cli release soon, so pls comment here if you start working on this. Otherwise I might do it myself. Thanks!

**Comment by krlmlr** [comment]
Starting work here.
