### ISSUE TITLE
Timings being printed in visual studio code

### ISSUE THREAD

**Issue by mkoohafkan** [r-lib/cli#412]
I originally posted this to https://github.com/REditorSupport/vscode-R/issues/942 but it seems to be an issue specific to `cli`. When using the vscode-R extension and official R terminal, packages that use `cli` to display messages are also printing what looks like timings. For example:

```r
library(tibble)
mtcars
as_tibble(mtcars)
```
![image](https://user-images.githubusercontent.com/4790348/153068849-438e4a4d-e46a-4608-a9eb-2bfcdb936191.png)

I am experiencing this with all packages that use `cli`, e.g., `devtools`, `tidyverse`, `targets`, etc. and it occurs consistently on multiple computers. It would be great to see this fixed. The current vscode-R suggestion is to use a different R terminal (radian) but there are a number of reasons why a user would not want to use an R terminal that depends on python and conda.

**Comment by gaborcsardi** [comment]
These are ANSI colors, which your terminal apparently cannot interpret. I am not sure why they are turned on, but nevertheless you can turn them off by setting an R option or an env var: https://cli.r-lib.org/reference/num_ansi_colors.html

**Comment by mkoohafkan** [comment]
THANK YOU SO MUCH. I guess vscode-R simply turns them on assuming users are using Radian (which presumably can print the colors). Seems like it should be an easy fix for the vscode-R developers to set that environment variable when the official R terminal is detected.

**Comment by mkoohafkan** [comment]
FYI this seems to be specifically occurring for Windows virtual machines. I am hitting this is issue on Windows Server 2016 VM, which I access via Window Remote Desktop Connection. Another user commented that they are having the same issue on a Windows 10 VM (not sure how they are accessing it but probably also RDC). Not sure if that's something that `cli` can detect in `num_ansi_colors()`.
