### ISSUE TITLE
Clearing up muddled licensing issues

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/cli#413]
Hi @gaborcsardi, I'm hoping you can help me clear up the somewhat muddled situation of licensing for the package.

It looks like a decent part of the src/ folder is copied from {utf8}, but the attribution is hit-or-miss. I'd like to identify which parts copied from upstream.

For example:

https://github.com/r-lib/cli/blob/main/src/charwidth.h

is just

https://github.com/patperry/r-utf8/blob/main/src/utf8lite/src/private/charwidth.h

But there's no tag in the {cli} file attributing it.

Then there's stuff like

https://github.com/r-lib/cli/blob/24a098b69c21c09baf662fee26b436f3aa0b679e/src/cli.h#L85-L88

which looks to be the same as

https://github.com/patperry/r-utf8/blob/447aa845e1ab00aef44e829aa91aab259c2e0ecc/src/utf8lite/src/utf8lite.h#L192-L195

utf8.c says it's "adapted from" {utf8}, but some parts appear to be copied, others not:

https://github.com/r-lib/cli/blob/main/src/utf8.c

Thanks

**Comment by gaborcsardi** [comment]
I would very much like to help you, but I am not entirely sure what you expect from me. Your statements are correct, cli does use parts of the utf8lite library, this is why I put that link in the source code. 

I don't know if that link counts as attribution, AFAIK the Apache license of utf8lite does not require attribution. But please correct me if I am wrong. 

True, there is no attribution at the beginning of the automatically generated files. But again, I don't think one is required there.

I will be happy to help with any questions you have.

**Comment by MichaelChirico** [comment]
Thanks Gabor. To clarify I don't think there's any compliance issue going on. This is to satisfy our one version policy:

https://opensource.google/documentation/reference/thirdparty/oneversion

Ideally we can remove any duplicated code from our fork of cli and patch the code to point to the upstream instead. I'm just hoping to avoid going through the source method-by-method to see which are copied / which are unique to cli. Any help you could offer would be great.

**Comment by gaborcsardi** [comment]
I see. You can't remove any code in this case I am afraid:
- one file (`utf8.c`) was heavily modified from the original.
- the header file only contains fragments and it is also modified.
- the two `.h` files are automatically generated with a script that is in utf8lite. It _might_ be true that they are identical to the copies in utf8lite currently, but these is nothing that ensures that. If we (or them) generate new tables based on a new Unicode edition, then they'll be different.

**Comment by MichaelChirico** [comment]
thanks Gabor, that's plenty helpful!! I think the rest is for us to sort out internally

**Comment by MichaelChirico** [comment]
Hey @gaborcsardi, maybe a LICENSE.note would be appropriate? Since utf8 is Apache-licensed.

That would be consistent e.g. with what's done in these r-lib repos:

 - https://github.com/r-lib/later/blob/main/LICENSE.note
 - https://github.com/r-lib/rlang/blob/main/LICENSE.note
 - https://github.com/r-lib/vctrs/blob/main/LICENSE.note
 - https://github.com/r-lib/vdiffr/blob/main/LICENSE.note
 - https://github.com/r-lib/tzdb/blob/main/LICENSE.note
