### ISSUE TITLE
`style_hyperlink()` and `rstudio:` prefix

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/cli#416]
Initially here: https://github.com/r-lib/testthat/pull/1544#discussion_r803969226

Maybe `style_hyperlink()` should handle url with prefix `rstudio:` when the `RSTUDIO_CLI_HYPERLINKS` env var is set, so that  these links are specific to rstudio.

**Comment by gaborcsardi** [comment]
I think this will be tackled at #456 in some way.
