### ISSUE TITLE
newlines in code formatted text throws error

### ISSUE THREAD

**Issue by zkamvar** [r-lib/cli#417]
My package uses cli to pass the output of a modified call to the user, which often has arguments wrapping to the next line. Version 3.2.0 now throws an error on newlines within `{.code }` formatted text:

``` r
cli::cli_text("{.code a & b}")
#> `a & b`
cli::cli_text("{.code a &\nb}")
#> Error in vapply(X, FUN, FUN.VALUE = character(1), ..., USE.NAMES = USE.NAMES): values must be length 1,
#>  but FUN(X[[1]]) result is length 2
```

<sup>Created on 2022-02-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
`{.code ...}` only works inline. I can make cli to replace `\n` with a space character, with an optional warning when that happens.
