### ISSUE TITLE
Q: How to preserve "everything" in an active sink?

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/cli#421]
Hi. My question is basically:

- Which options should be set, and to what values, for **cli** to behave identically inside an active sink as outside?

As the below example shows, I figured out that I need to set options `cli.num_colors = cli::num_ansi_colors()` to preserver colors.  Are there other options one need to consider to preserve "everything" that **cli** can output via stdout and conditions.

```r
library(cli)
cli_test <- function() {
  cli_alert_danger("watch out\n")
}

# Default without active sink
options(cli.num_colors = NULL)
cli_test()
#> ✖ watch out   # ✖ in RED

# Default with active sink
options(cli.num_colors = NULL)
void <- utils::capture.output(cli_test())
#> ✖ watch out   # No colors

# Preserve colors with active sink
options(cli.num_colors = cli::num_ansi_colors())
void <- utils::capture.output(cli_test())
#> ✖ watch out   # ✖ in RED
```

This is with cli 3.2.0 with R 4.1.2 running in a Linux terminal.

**Comment by gaborcsardi** [comment]
FWIW `cli_format_method()` does this:

```r
  nc <- num_ansi_colors()
  opts <- options(
    cli.num_colors = nc,
    crayon.enabled = nc > 1,
    crayon.colors = nc
  )
  on.exit(options(opts), add = TRUE)
```

Of course R internals are different when there is a sink, and there is no perfect solution. E.g. on (msvcrt) Windows the output is UTF-8 in a GUI, but ASCII in a sink.

**Comment by HenrikBengtsson** [comment]
Thanks, @gaborcsardi, then I'll use those options.

> Of course R internals are different when there is a sink, and there is no perfect solution. E.g. on (msvcrt) Windows the output is UTF-8 in a GUI, but ASCII in a sink.

For others reading this, I think this refers to the following issue on MS Windows that we currently have:

```r
# R 4.1.2 and before
> cat("\u2713 hello\n")
[1] "✓ hello"
> utils::capture.output(cat("\u2713 hello\n"))
[1] "<U+2713> hello"
```

Note how the UTF-8 symbol ✓ is escaped into an ASCII sequence.  In the upcoming R 4.2.0, we'll have much better UTF support also on MS Windows;

```r
# R-devel (to become R 4.2.0)
> cat("\u2713 hello\n")
[1] "✓ hello"
> utils::capture.output(cat("\u2713 hello\n"))
[1] "✓ hello"
```

**Comment by gaborcsardi** [comment]
> Note how the UTF-8 symbol ✓ is escaped into an ASCII sequence. In the upcoming R 4.2.0, we'll have much better UTF support also on MS Windows;

Well, that is only true in recent Windows 10 and Windows Server 2022.

**Comment by HenrikBengtsson** [comment]
> > Note how the UTF-8 symbol ✓ is escaped into an ASCII sequence. In the upcoming R 4.2.0, we'll have much better UTF support also on MS Windows;
> 
> Well, that is only true in recent Windows 10 and Windows Server 2022.

Thanks, I wasn't aware (but now when you say it, it makes sense). This info is helpful for my work on futures.
