### ISSUE TITLE
Get rid of the RStudio symbol set

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#424]
It causes issues: https://github.com/tidyverse/tidyverse/issues/256

We'll just use ASCII on Windows, in RStudio as well. And get rid of the Windows symbol set as well.

**Comment by light2802** [comment]
I would like to contribute to this issue.

**Comment by dpprdan** [comment]
Possibly make this dependent on UTF-8 support (UCRT in R 4.2+)?
