### ISSUE TITLE
How to use spinners in code?

### ISSUE THREAD

**Issue by gregleleu** [r-lib/cli#43]
Hi, 
I couldn't figure out how to use the spinners in code, while an lapply function is running. 
What should it look like? Maybe it could be useful to add it to the readme/package pdf?
Thanks!
Greg

**Comment by gaborcsardi** [comment]
You can just `cat` `paste0("\r", spinner$frames[i])` to the screen, while the function is running. It is not good to do it too often, because `cat` has a cost.

You can also use the progress package with a custom token.

Yeah, an example would be nice, would you like to submit one with the progress package?

**Comment by samssann** [comment]
Do you have any suggestions on how to use spinners with an arbitrary function? What I've tried so far:
- your `callr` package with r(fun, show = T) 
drawbacks: function evaluated in another session which can be tricky is some cases and user can't set the spinner type or the output message.
- the `future` package, but the output is only relayed (https://cran.r-project.org/web/packages/future/vignettes/future-2-output.html, https://github.com/HenrikBengtsson/future/issues/141)
- your `processx` package 
```
spin <- function() {
  name = "test"
  sp <- cli::get_spinner("line")
  interval <- sp$interval/1000
  frames <- sp$frames
  cycles <- max(round(2.5/((length(frames) - 1) * interval)), 1)
  while(T) {
    for (i in 1:(length(frames) * cycles) - 1) {
      cat("\r", name, cli:::rpad(unclass(frames[i %% length(frames) + 1]), width = 10), sep = " ")
      Sys.sleep(interval)
    } 
  }
}
x <- r_process$new(r_process_options(func = spin))
processx::conn_set_stdout(x$get_output_connection())
Sys.sleep(10) # <your_long_running_function_here>
x$kill()
```
But I can't get the output attached to the current r session.

The ideal case would be if there would be a wrapper function called e.g. `spinr` and could use it by just inserting the function as an argument
`randomFunction() %>% spinr('line')`
and it would spin as long as function is running. The `processx ` way (described above) could be valid if the output can be redirected to the current R session.

**Comment by gaborcsardi** [comment]
> and it would spin as long as function is running

that does not work, because R is single threaded. Currently the  spinners are only useful if you write your own event loop, unfortunately.

**Comment by samssann** [comment]
Here is one approach with `future` package (modified from https://github.com/HenrikBengtsson/future/issues/141#issuecomment-292743988)

```
library(future)
library(cli)
plan(multisession)

spinr <- function(fun, name, spinner) {
  expr <- substitute(fun)
  # spinner configuration
  spinner <- match.arg(spinner, choices = list_spinners())
  sp <- get_spinner("line")
  interval <- sp$interval/1000
  frames <- sp$frames
  cycles <- max(round(2.5/((length(frames) - 1) * interval)), 1)
  # parallel execution
  future_fun <- future(expr, substitute = F)
  # spinner loop
  while (!resolved(future_fun)) {
    for (i in 1:(length(frames) * cycles) - 1) {
      cat("\r", name, cli:::rpad(unclass(frames[i %% length(frames) + 1]), width = 10), sep = " ")
      Sys.sleep(interval)
    } 
  }
  tryCatch(
    {
      out <- value(future_fun)
      cat("\r", name, cli::symbol$tick, sep = " ")
      cat("\n", file = stderr())
      out
    },
    error = function(e) {
      cat("\r", name, cli::symbol$cross, sep = " ")
      cat("\n", file = stderr())
      stop(e$message)
    }
  )
}

funOK <- function(x) {
  Sys.sleep(3)
  return(x)
}

funFAIL <- function(x) {
  Sys.sleep(3)
  stop("asd")
}

spinr(funOK("test"), "testing", "line")
spinr(funFAIL("test"), "testing", "line")

testing ✔         
[1] "test"

testing ✖         
Error in value[[3L]](cond) : asd
```

**Comment by gaborcsardi** [comment]
There is now a `make_spinner()` helper function (#65) that you can use to create a spinner, or you can write your own helper function based on that.
