### ISSUE TITLE
Hide cli messages in testthat()

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/cli#434]
[First asked on [StackOverflow](https://stackoverflow.com/questions/71406719/hide-cli-messages-in-tests-with-testthat)]

Hello, I'm not sure if this issue belongs here or in `testthat` repo. I use `cli` messages in one of my packages. I would like to hide these messages in my tests because they clutter the testthat results. Is there a way to do that?

I've seen that `cli` has an internal environment variable called [TESTTHAT](https://cli.r-lib.org/reference/cli-config.html#testthat) but I don't know if it exists for this purpose, and I don't know how to use it. 

Reproducible example:
```r
library(testthat)
library(cli)

test_that("addition works", {
  cli_alert_info("This message should not appear")
  expect_equal(1+1, 2)
})

#> i This message should not appear
#> Test passed 
```
I could create a custom `test_that()` that would wrap `suppressMessages()` like the following:
```r
my_test_that <- function(desc, code) {
  test_that(desc, {
    suppressMessages({
      code
    })
  })
}

my_test_that("addition works", {
  cli_alert_danger("This message should not appear")
  expect_equal(1+1, 2)
})

#> Test passed 
```
and then store it in `tests/testthat/setup.R`. The problem is that if a test fails, it indicates the line in `my_test_that()` and not the line where the error actually appears (so basically all errors and warnings will refer to the same line):
```r
my_test_that("addition works", {
  cli_alert_danger("This message should not appear")
  expect_equal(1+4, 2)
})

-- Failure (.active-rstudio-document:6:5): addition works ----------------------
1 + 4 (`actual`) not equal to 2 (`expected`).
```
Here, the error refers to the line with `suppressMessages()`. This makes it much harder to find the source of the problem. Is there a way to hide cli messages in a testing environment?

**Comment by gaborcsardi** [comment]
You can set the `cli.default_handler` option, probably with withr::local_options(), within the tests:

```r
❯ cli::cli_text("hello")
hello

❯ options(cli.default_handler = function(...) { })
❯ cli::cli_text("hello")

❯ options(cli.default_handler = NULL)
❯ cli::cli_text("hello")
hello
```

One issue with this is that if a testthat reporter is going to use cli in the future, then those messages will be suppressed as well. So ideally this would need some changes in testthat, to protect against that.

**Comment by etiennebacher** [comment]
Thanks for the solution! I modified `test_that()` like the following:
```r
my_test_that <- function(desc, code) {
  withr::with_options(
    list(
      cli.default_handler = function(...) { },
      usethis.quiet = TRUE
    ),
    test_that(desc, {
      code
    })
  )
}

my_test_that("addition works", {
  cli_alert_danger("This message should not appear")
  expect_equal(1+2, 2)
})
```
which seems to report the correct line number when sourcing the document. One issue though is that `testthat::expect_message()` will fail in `my_test_that()`. I think this is what you meant with:

> One issue with this is that if a testthat reporter is going to use cli in the future, then those messages will be suppressed as well. So ideally this would need some changes in testthat, to protect against that.

Should I move this issue to testthat repo?

**Comment by gaborcsardi** [comment]
That's not really what I meant. 

If you set `cli.default_handler` then there will be no messages, so you cannot use `expect_message()`. 

For the test cases you want to use `expect_message()` for, you cannot set `cli.default_handler()`.
