### ISSUE TITLE
"Building a Semantic CLI" vignette has misplaced asciicast svgs.

### ISSUE THREAD

**Issue by pwseo** [r-lib/cli#435]
For some reason, the code present at the `asciicast` block in [line 207](https://github.com/r-lib/cli/blob/HEAD/vignettes/semantic-cli.Rmd#L207) isn't rendered, and what's rendered instead is the next `asciicast` block. All remaning `asciicast` blocks after this point render before they were supposed to, resulting in a confusing vignette, like in the following screenshot:
![image](https://user-images.githubusercontent.com/95953/158028744-395797d6-9abe-49ed-8371-7288ed76e276.png)
I have tried this in multiple browsers, it does not seem to be a local issue.

**Comment by gaborcsardi** [comment]
Thanks for reporting this! Will fix soon.

**Comment by gaborcsardi** [comment]
Fixed in the dev docs currently: https://cli.r-lib.org/dev/articles/semantic-cli.html#lists

Will be fixed in the released docs as well, when the release happens.
