### ISSUE TITLE
No code formatting with `{.code }`

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/cli#436]
In the [docs](https://cli.r-lib.org/articles/usethis-ui.html#usethisui_code), it is said that `usethis::ui_code()` can be replaced with `{.code }`, but it seems that the coloring doesn't work with the latter:
```r
usethis::ui_done("Redocument with {usethis::ui_code('devtools::document()')}")
cli::cli_alert_success("Redocument with {.code devtools::document()}")
```
I can't show the difference of output on Github but `devtools::document()` is not colored and appears as plain text when using `{.code devtools::document()}`. The formatting works well with other classes, e.g `field` or `val`.

I'm using the Github version of `cli`.

**Comment by gaborcsardi** [comment]
The default theme does not color code, only puts it in backticks. You can change this if you like, put this in your profile:

```r
options(cli.user_theme = list(.code = list(color = "grey")))
```

**Comment by etiennebacher** [comment]
Thanks, this works but it's just for me. If I want this option to work for all cli messages that were created in my functions, how should I do this?

**Comment by gaborcsardi** [comment]
Like this:
```r
cli_div(theme = list(.code = list(color = "grey")))
cli::cli_alert_success("Redocument with {.code devtools::document()}")
```

At some point cli will have package-specific themes as well. OTOH it might be a good idea not to control the theme too much in a package, so the end user can specify it for all packages that use cli.

**Comment by etiennebacher** [comment]
Got it, thank you
