### ISSUE TITLE
Provide style similar to .val without adding quotes

### ISSUE THREAD

**Issue by thomasp85** [r-lib/cli#443]
When having literals in an error message it is nice that they stand out. `.val` does that but it also adds quotes, making the literal appear as a string. A style aligned with `.val` but without quotes would be a nice addition

**Comment by gaborcsardi** [comment]
@thomasp85 Can you give some examples when you'd use this? 

We already have `.val` which calls the `cli_format` generic, by default meaning `encodeString()` and it also adds color. 

We also have `.str` which calls `encodeString()` but does not add color.

For emphasis we have `.emph` and `.strong`.

It feels like you just want emphasis but not `encodeString()`, and color instead of italic and bold.

**Comment by thomasp85** [comment]
I guess my main motivation was to have a way to consistently format literals in messages such as `clip must be TRUE, 1, or "on"` (very contrived example). Here it would be nice if `TRUE`, `1`, and `"on"` all had the same formatting and I thought that was the intend of `{.val }` but quotes around numbers and logicals looks off (and wrong)

**Comment by gaborcsardi** [comment]
I don't think `.val` adds quotes to logicals:
```r
cli::cli_text("clip must be {.val {TRUE}}, {.val {1}}, {.val {'on'}} (very...")
```
<img width="727" alt="Screen Shot 2022-08-23 at 3 28 15 PM" src="https://user-images.githubusercontent.com/660288/186170452-3c05c553-6b98-4905-b749-ca85b4797c4e.png">

It would be great to be able to write 
```r
vals <- list(TRUE, 1, 'on')
cli::cli_text("clip must be {.val {vals}}")
```
but that's currently buggy, and always omits the quotes.

**Comment by thomasp85** [comment]
Hmm that's odd. I remember this being exactly the reason why I opened it. Has there been some recent changes that have fixed this behaviour?

In any way, this can then be closed I think

**Comment by gaborcsardi** [comment]
I don't think so. Maybe you wrote `{.val TRUE}` instead of `{.val {TRUE}}`. The former is quoted, as cli has no idea that it is a logical value.
