### ISSUE TITLE
.help inline formatter

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#457]
Automatically generates RStudio doc link (see details at https://github.com/rstudio/rstudio/blob/a912e075aa428e11025e0444d382cd39037aaa06/src/cpp/session/modules/SessionConsole.R)

**Comment by gaborcsardi** [comment]
Things cli should generate be able to generate: https://github.com/rstudio/rstudio/issues/11273#issuecomment-1156193252

**Comment by gaborcsardi** [comment]
Will add this together with #456.
