### ISSUE TITLE
Provide friendly_type?

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#463]
It'd be nice to be able to write:

```R
abort("`{.arg levels} must be a character vector, not a {.friendly levels}")
```

And know that the user is going to get something that makes sense to them.

**Comment by gaborcsardi** [comment]
Re the implementation, in general `{.class ...}` only does styling and not other evaluation and it also does not have information about the frame where the error was thrown. But we could have functions that return some `cli::cli_vec()` objects, that have a desired style, after the appropriate processing. We could add a `class` argument to `cli_vec()` to make it easier to return a vector with a cli class.

**Comment by hadley** [comment]
Oh yeah, this would be fine as a function too. I think this particular one belongs in cli because it's so needed in so many places.

**Comment by hadley** [comment]
Collection of places we've defined this before:

* `ggplot2:::obj_desc`
* `rlang:::friendly_type_of`
* `R7::obj_desc`
