### ISSUE TITLE
Favour new RStudio env vars over existing heuristics

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#465]
https://github.com/rstudio/rstudio/issues/11024

Obviously will want to keep heuristics for some time (probably several years), until this version of RStudio is in widespread usage.

**Comment by gaborcsardi** [comment]
Maybe. OTOH the current detection should also detect the build pane correctly, I believe, so maybe this is not the reason?

**Comment by romainfrancois** [comment]
related to https://github.com/rstudio/rstudio/pull/11281

**Comment by DavisVaughan** [comment]
A few concrete differences between `Run Tests` on a single file and CMD+SHIFT+T that hopefully can be resolved:

- `Run Tests` doesn't have color
- `Run Tests` links to files, like `test-vec-case-when.R`, but doesn't link `snapshot_accept()`


<img width="737" alt="Screen Shot 2022-05-23 at 6 37 16 PM" src="https://user-images.githubusercontent.com/19150088/170043794-5c07f9ae-d12c-4750-a8cd-95c525da4c94.png">
<img width="827" alt="Screen Shot 2022-05-24 at 9 12 49 AM" src="https://user-images.githubusercontent.com/19150088/170043800-9fe8f03f-d17f-4f11-a081-12db67196e36.png">

**Comment by hadley** [comment]
If I install https://github.com/r-lib/rlang/pull/1404 and `devtools::document()`, I don't see colour working in the build pane either, so I think the current heuristics fail for more than just "Test file".

**Comment by romainfrancois** [comment]
Maybe ? related to `local_reproducible_output(.env = )`

https://github.com/r-lib/testthat/blob/0f24eae7bd2cd7d0fbe5a5492636731d66d0dd26/R/local.R#L106

**Comment by gaborcsardi** [comment]
@hadley The "Run tests" button wasn't detected with the old methods, I fixed that as well in #471. I probably only looked at the commands in the Build menu....

@DavisVaughan What does CMD+SHIFT+T run?

**Comment by DavisVaughan** [comment]
@gaborcsardi It runs `devtools::test()` in the Build pane (which I am fairly certain is in a new R session)
