### ISSUE TITLE
Casing consistency of theme properties

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#483]
Most properties are dash-cased except these ones which are snake_cased: `vec_last`, `vec_sep`, `vec_trunc`, and `string_quote`. Should the latter be superseded in favour of dash-cased properties?

**Comment by lionel-** [comment]
Maybe also replace all dashes by underscores in property values, so that `color = "br-blue"` is equivalent to `color = "br_blue"`?

**Comment by gaborcsardi** [comment]
Many style names are coming from CSS, so I will rather change the underscores into dashes.
