### ISSUE TITLE
Trailing newlines ignored

### ISSUE THREAD

**Issue by davidchall** [r-lib/cli#491]
In functions with wrapping, we use the form feed character "\f" to force a newline. I've found that this is handled inconsistently though. If the form feed is at the end of the string, then it is ignored.

``` r
# middle: works
cli::cli_text("a\fb")
#> a
#> b

# start: works
cli::cli_text("\fb")
#> 
#> b

# end: fails
cli::cli_text("a\f")
#> a
```

<sup>Created on 2022-06-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
Forgot if this was intentional but multiple `\f` newlines are also not preserved:
```r
❯ cli::cli_text("a\f\f\fb")
a
b
```

**Comment by gaborcsardi** [comment]
I fixed the trailing `f`. Multiple `\f` are still collapsed, though. IDK if this is an issue.

**Comment by davidchall** [comment]
Thanks a lot, @gaborcsardi!

For my purposes (described in #490), I do need consecutive \f characters to be preserved. Should I open a separate issue for this?

**Comment by gaborcsardi** [comment]
Let's reopen this one then.
