### ISSUE TITLE
Add `style_hyperlink_run()`?

### ISSUE THREAD

**Issue by lionel-** [r-lib/cli#499]
We're using this helper to create clickable links to run code:

https://github.com/r-lib/pkgload/commit/8557ca07d722d892685eed527a0a39ac3f361f43#diff-60bef5af43a1bd541299ce9bceeb226afb23deaa5e637b145c85e05ffd552b0cR192-R199

```r
style_hyperlink_run <- function(code) {
  if (nzchar(Sys.getenv("R_CLI_HAS_HYPERLINK_RUN"))) {
    link <- paste0("rstudio:run:", code)
    code <- cli::style_hyperlink(code, link)
  }

  cli::format_inline("{.code {code}}")
}
```

cc @romainfrancois

**Comment by hadley** [comment]
Duplicate of #456?

**Comment by lionel-** [comment]
Closing as duplicate.
