### ISSUE TITLE
Text in the rules (cli_rule and cat_rule)

### ISSUE THREAD

**Issue by avraam-inside** [r-lib/cli#500]
### Introduction
***

Hi! I want to color my rules, but I don't need to color the text inside the rule. It doesn't look very good, in my and my colleagues' opinion. So, I have to color the text in the standard letter color of the current RStudio theme, but there is a big problem.

<br> 

### Problem
***

In my working practice, different people use different RStudio themes, dark, white and others (rarely, but they also occur). And I have to write a lot of ugly add-ons to handle these cases, while they work poorly, some themes return me incorrect information about the color of the main letters in `rstudioapi::getThemeInfo()`, and also, for example, the pure white color `"#000000"` is not as bright as the RStudio theme:

![image](https://user-images.githubusercontent.com/52919010/184113362-fca7ea4e-137d-4392-b2d5-ef5c6d37d1c6.png)

Especially a lot of problems arise when I have to parse the saved text in a log file with cli coloring back to the console in another RStudio theme. I used a white theme on my car, and a black one on someone else's car. Or if the script was run from under linux without rstudioapi - it is also not clear what color to paint.

<br>

### Request
***

Please make sure that `cli_rule` and `cat_rule` color the text in the standard color of the letters of the current RStudio theme, and the color of the RULE does not affect the text in it. I.e., isolate the line color from the text color.

It will look normal and work correctly. If I need to colorize the text in the rule, I can define it. But in my practice - I do not have such an opportunity.

**Comment by gaborcsardi** [comment]
> Hi! I want to color my rules, but I don't need to color the text inside the rule.

`cat_rule()` has an argument to only change the line color:
<img width="891" alt="Screen Shot 2022-08-11 at 9 01 58 PM" src="https://user-images.githubusercontent.com/660288/184219234-cf1157de-856c-4424-9a62-da0925a21507.png">

**Comment by avraam-inside** [comment]
Hi! I've been digging for a long time, but I haven't seen such a simple trick before (

There is no problem. Thanks!
