### ISSUE TITLE
Bullets are lost when using external vectors inside `cli_bullets(text)`

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/cli#505]
Hi,

Not sure if this is a bug report or a feature request, but it seems that bullets are lost if one uses an external vector inside the `cli_bullets(text)` vector:

``` r
pb=c("here", "there")
cli::cli_bullets(c("There is a problem in several places",
              x=pb[1],
              x=pb[2]))
#> There is a problem in several places
#> ✖ here
#> ✖ there
cli::cli_bullets(c("There is a problem in several places",
              x=pb))
#> There is a problem in several places
#> here
#> there
```

<sup>Created on 2022-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
Your vector components are not named `x`, though:

``` r
pb <- c("here", "there")
c("There is a problem in several places", x=pb)
#>                                                                            x1 
#> "There is a problem in several places"                                 "here" 
#>                                     x2 
#>                                "there"
```

<sup>Created on 2022-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
IDK if we should extract the first character of the name and use that. It does seem to make sense for your thing, but it also restricts the extensions of the API in the future.

**Comment by DanChaltiel** [comment]
For now [`cli_bullet()`](https://cli.r-lib.org/reference/cli_bullets.html) documentation only cites names without a number.  
My example with names `c("x1", "x2")` is actually a misuse of the API (sorry 😁) as these are not documented. Hopefully, the API doesn't stop but kindly treats any unknown name as `no name`, without even a warning.

Therefore, you could decide to also manually remove all digits from `names(text)` without contradicting the documentation at all. This would only extend the "kindness" of the API, which we can be grateful for but not complain about if it ever goes away.

If in the future it seems really necessary to have numbers in bullet names, you could always revert this change silently.

**Comment by gaborcsardi** [comment]
Yeah, I thought about this, and I am not sure how often this comes up. Also, maybe it is simpler to handle this with a helper function that assigns the right names to each element of the vector.

**Comment by DanChaltiel** [comment]
A helper would be indeed easy to write but would make the syntax rather more verbose.

I'm a bit confused about how this was completed, shouldn't this issue be closed as "not planned" instead?
