### ISSUE TITLE
Proposition: align text by internal pattern

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/cli#506]
Hi,

Here is a little helper I needed that might be useful to others (somewhere between `ansi_columns()` and `ansi_align()`):

``` r
library(cli)
ansi_align_by = function(text, pattern){
  pos = gregexpr(pattern, ansi_strip(text)) |> unlist()
  spaces = strrep("\u00a0", max(pos)-pos)
  stringr::str_replace(text, pattern, paste0(spaces, pattern))
}

x=c(
  paste(col_red("red"), "-->", col_green("green")),
  "x='A' --> y='B", 
  "foo='A' --> bar='B", 
  "azertyuiopqs='A' --> foobar='B"
)

x |> ansi_align_by("-->") |> cat(sep="\n")
#> red              --> green
#> x='A'            --> y='B
#> foo='A'          --> bar='B
#> azertyuiopqs='A' --> foobar='B
```

<sup>Created on 2022-08-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I'm rather sure that this code is below standard for this package but I can make a PR if that's helpful.

**Comment by gaborcsardi** [comment]
Thanks! Unfortunately this gets much harder if you want to support ANSI markup.

**Comment by DanChaltiel** [comment]
At least for simple markup like color here, this works actually quite fine (colors are shown on RStudio but not on GitHub), but indeed I don't know about more complex markups.

However, it seems that all `cli_` functions squish text before printing, so my code turns out to be useless in this form 😢 
``` r
cli::cli_text("A      --> B")
#> A --> B
```
