### ISSUE TITLE
Allowing options of glue::glue to be available to cli functions

### ISSUE THREAD

**Issue by trickytank** [r-lib/cli#509]
In particular, I would like to be able to set `.trim = FALSE` when calling cli_text.

**Comment by gaborcsardi** [comment]
cli has its own trimming, when wrapping the text, so that would not change much, I am afraid. What is the problem that you are trying to solve?

**Comment by gaborcsardi** [comment]
I just removed the trimming from cli, and all test cases still pass, so it probably does not have any effect.

**Comment by trickytank** [comment]
Hi @gaborcsardi, 

I was just trying to get 
```
cli_text("  Score:    {score}")
```
To not trim whitespace. After further exploration maybe I should just be using the cat_line() function?

**Comment by gaborcsardi** [comment]
Yeah, we don't have tools for alignment yet, sorry. Coming in #229. 

As a workaround you can use the Unicode non-breaking space (`\u00a0`), that is not trimmed, but it is a pain in the neck. Will work on #229 soon...

```r
just <- function(x) gsub(" ", "\u00a0", x)
score <- 50
cli_text(just("  Score:    {score}"))
#>   Score:    50
```

**Comment by trickytank** [comment]
Thanks
