### ISSUE TITLE
Usage of cli with BiocParallel results in "Active theme colors not available" warnings in RStudio

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/cli#512]
Hi, I'm seeing an `"Active theme colors not available."` warning pop up specifically when calling cli (v3.3.0) functions inside of BiocParallel (v1.30.3) functions. This appears to be occuring only when run inside RStudio but not R from the command line.

```r
BiocParallel::bplapply(
    X = c("foo", "bar"),
    FUN = function(x) {
        cli::cli_alert(x)
        invisible(x)
    }
)
```

```
## Warning in (function ()  : Active theme colors not available.
## Calls: <Anonymous> ... <Anonymous> -> callFun -> do.call -> <Anonymous> -> .Call
## → foo
##
## Warning in (function ()  : Active theme colors not available.
## Calls: <Anonymous> ... <Anonymous> -> callFun -> do.call -> <Anonymous> -> .Call
## → bar
```

These variants work without issue:

```r
lapply(
    X = c("foo", "bar"),
    FUN = function(x) {
        cli::cli_alert(x)
        invisible(x)
    }
)
```

```
parallel::mclapply(
    X = c("foo", "bar"),
    FUN = function(x) {
        cli::cli_alert(x)
        invisible(x)
    }
)
```

**Comment by mjsteinbaugh** [comment]
It appears that this documentation on environment variables may be relevant:
https://cli.r-lib.org/reference/cli-config.html

**Comment by gaborcsardi** [comment]
I can't reproduce this. Also, that error message is not coming from cli.

Can you tell us what versions of packages and RStudio you are using, and also with which theme?

**Comment by mjsteinbaugh** [comment]
Weird right? RStudio 2022.07.1 Build 554. Doesn't seem to matter what theme is set. I see it pop up with Textmate (default).

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.5.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocParallel_1.30.3 cli_3.3.0          

loaded via a namespace (and not attached):
[1] compiler_4.2.1   parallel_4.2.1   tools_4.2.1      codetools_0.2-18
```

I'll test and see if this also pops up for me on RStudio Server in a little bit.

**Comment by gaborcsardi** [comment]
I suspect that this is coming from the `rstudioapi` package, so that should be loaded as well?

**Comment by mjsteinbaugh** [comment]
I'm not seeting rstudioapi in sessionInfo but it's 0.14 on my machine

**Comment by mjsteinbaugh** [comment]
I tried downgrading rstudioapi to 0.13 just to compare, and I still see the warnings pop up, so it doesn't appear to be specific to 0.14

**Comment by gaborcsardi** [comment]
rsutdioapi should be loaded in the subprocess. Anyway, it is coming from here-ish:
https://github.com/rstudio/rstudio/blob/b93d2cf774950c8f2c087f449beb91986b16329f/src/cpp/session/modules/SessionThemes.cpp#L374
https://github.com/rstudio/rstudio/blob/ec781aad4a3be2398a2ec0cb8b7678934ed59ff4/src/cpp/r/R/Api.R#L898
and I suspect that something in your RStudio config triggers it. 

In any case, we can ignore these warnings in cli, we already handle the case when the theme data is not reported.

**Comment by mjsteinbaugh** [comment]
@gaborcsardi Awesome thanks for the quick fix! Resolved the issue on my machine
