### ISSUE TITLE
From html or markdown to cli

### ISSUE THREAD

**Issue by sda030** [r-lib/cli#516]
### Feature request:
Perhaps there is a straight forward solution. I need to convert basic markdown (or possibly html) stored as a string to prettified console output. By basic I mean h1, h2, h3, emphasis, strong, url, bullets, lists, etc. {cli} can print all of this if specified as functions, but conversion (```as_cli()``` or ```print.html```) does not seem to exist? I do not find any such function in the markdown, rmarkdown, fansi, or htmltools. 

The benefit of such a feature is that packages can be created using markdown which can alternatively print a simplified version to the console instead of a more time-consuming rendering of html.
If this is considered beyond the scope of cli, suggestion for where such functionality should be placed would be welcome.

**Comment by gaborcsardi** [comment]
Thanks! This is out of scope for cli currently.
