### ISSUE TITLE
Links to the manual do not work with topics that contain a dot

### ISSUE THREAD

**Issue by SigurdJanson** [r-lib/cli#524]
I seem to have trouble with [links to the manual](https://cli.r-lib.org/reference/links.html#links-to-the-manual). Maybe someone can help? Is this a `cli` problem or an R-Studio problem or neiter?

I get a working link for `{.topic [table](base::table)}` but **not** for `{.topic [as table](base::as.table)}`.

#### Wrong behaviour:
``` r
cli::cli_text("Clicking on {.topic [as table](base::as.table)} will not help.")
```
This first sample shows a broken tool tip. There is no chance to click the link.
![grafik](https://user-images.githubusercontent.com/59577271/190494746-51fed18e-8ae7-4d26-b9fa-213ea70156c5.png)

#### Expected behaviour:
``` r
cli::cli_text("Clicking on {.topic [table](base::table)} will help.")
```

The second one works:
![grafik](https://user-images.githubusercontent.com/59577271/190494970-9eb834d1-30d9-4ece-abb2-56a1f3102e4f.png)

#### Additional Observations to pin down the problem:

Not only `.topic` is affected (and not only `as.table` - I tried a few more):  

``` r
cli::cli_text("{.help [data frame](base::data.frame)} does not help.") # has a "." and does not work
cli::cli_text("{.help [data matrix](base::matrix)} helps.") # works

cli::cli_text("{.topic [data frame](base::data.frame)} does not help.")
cli::cli_text("{.topic [data matrix](base::matrix)} helps.")
```
However, running it in a ["no-link environment"](https://cli.r-lib.org/reference/links.html#without-hyperlink-support-2) does not cause any problems. The following output is correct:

``` r
local({
  withr::local_options(cli.hyperlink = FALSE)
  cli::cli_text("{.help [data frame](base::data.frame)}")
  cli::cli_text("{.help [data matrix](base::matrix)}")
  
  cli::cli_text("{.topic [data frame](base::data.frame)}")
  cli::cli_text("{.topic [data matrix](base::matrix)}")
})
#> data frame (`?base::data.frame()`)
#> data matrix (`?base::matrix()`)
#> data frame (`?base::data.frame`)
#> data matrix (`?base::matrix`)
```
<sup>Created on 2022-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

We can also rule out that the help topic does not exist. The tool tip would point that out. See the second example. It shows a tool tip saying "_documentation not found_". Clicking it will say the same. `{.fun base::data.frame}`, however, does not let me click the link in the first place.

``` r
cli::cli_text("... {.fun base::data.frame} ...")
#> ... `base::data.frame()` ...
cli::cli_text("... {.fun base::data_frame} ...")
#> ... `base::data_frame()` ...
```

**Environment:**
``` r
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
[3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.1  cli_3.4.0       tools_4.2.1     rstudioapi_0.14
```

**Comment by gaborcsardi** [comment]
cli seems to generate the correct ANSI sequence, so this is an RStudio bug, I think. @romainfrancois ?

```r
> cli::format_inline("{.topic [as table](base::as.table)}")
[1] "\033]8;;ide:help:base::as.table\aas table\033]8;;\a"
```

**Comment by gaborcsardi** [comment]
I am going to close this here, since there is nothing to do in cli.

**Comment by romainfrancois** [comment]
and this is fixed in rstudio: https://github.com/rstudio/rstudio/issues/11983
