### ISSUE TITLE
col_silver doesn't change colour back to defaults in emacs (ESS)

### ISSUE THREAD

**Issue by bramburger** [r-lib/cli#538]
Dear r-lib/cli developers,

I am using R with ESS in emacs, using a low contrast colour scheme. I have been running into some difficulties where some R code is changing the colours of the output, and subsequently all the output becomes nearly invisible. With a bit of searching it looks like the problem comes from a call to the `col_silver` function from this package. I have attached a screenshot to show what happens.

A call to `col_blue` or `col_black`, for example, changes the colour of the output and then changes the colour back the defaults of the colour scheme for subsequent input and output. However, after a call to `col_silver` everything following that call is coloured "silver" until I end the session (at which point output returns to the defaults of the colour scheme).

This problem does not occur for me in a terminal (like alacritty or rxvt), but of course that doesn't let me edit and run selected lines of code from a *.R file.

This example uses `cli` directly, but the problem more generally occurs when there is output in the from of a `tibble` kind of data frame or errors from `ggplot`.

Is this something that could be addressed, please?
And is there something I can do for now on my end to stop this package from changing colours?

Thank you kindly,
Bram

![cli_colours_ess](https://user-images.githubusercontent.com/23635555/198227717-2b5033e4-c201-4ee4-b293-57a5f1703225.png)

**Comment by gaborcsardi** [comment]
The same happens for 
```r
cat("not\033[90msilver\033[39mnot\n")
```
but only in Emacs, so I am afraid that this is an Emacs bug. I don't think that we can work around it, other than turning off bright colors in Emacs completely.

**Comment by bramburger** [comment]
Thank you for your quick response!
I don't know the particulars and have no idea how those codes work, so I'm afraid I can't give any suggestion in that regard. :-)

For me, I would much rather be able to read the output (and subsequent input), so if there is a way I can turn off bright colours (or even better, all colours) that would be preferable to how it is now. Is there an option to do that?

**Comment by gaborcsardi** [comment]
Sure, you can turn off colors, set the `NO_COLOR` env var to `true`, see `?cli::num_ansi_colors`.

**Comment by bramburger** [comment]
Ah, wonderful! Somehow managed to miss that. Thank you! Have a wonderful day.
