### ISSUE TITLE
wrong color output when using the col_green or bg_green functions

### ISSUE THREAD

**Issue by bucky2177** [r-lib/cli#547]
Hi,

first, thanks a lot for this nice package.

When using the col_green or col_blue (or their bg_<> counterparts), I noticed that the corresponding output seems wrong. What should be green is printed out blue, and vice versa. Interestingly, I noticed this issue after updating R to the most recent version. 

Here is the code I run:
library(cli)
col_green("Hello World")

Thanks a lot in advance :)

Best, 
Valentin

Here is my sessionInfo()

R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000) NOTE: I just noticed that this might be wrong, I run Windows 11

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cli_3.4.1

loaded via a namespace (and not attached):
[1] compiler_4.2.2  magrittr_2.0.3  tools_4.2.2     rstudioapi_0.14

RStudio Version: 2022.07.2
![Screenshot 2022-12-13 120450](https://user-images.githubusercontent.com/24256986/207301241-26bec3c4-bf33-420e-bcc7-2ffa4a1d9515.png)

**Comment by gaborcsardi** [comment]
Can you try this?
```r
cat("\033[32mHello world!\033[39m")
```

If this is also not green, then probably your terminal has its own color palette and it maps green to blue.

**Comment by bucky2177** [comment]
Yes, this again leads to a blue output.

**Comment by gaborcsardi** [comment]
That means that this is coming from your terminal, and not cli, so I am afraid we cannot do anything about it.
