### ISSUE TITLE
inserting linebreaks to `cli_abort` error messages

### ISSUE THREAD

**Issue by selkamand** [r-lib/cli#559]
Thanks for all your work on this incredible package!

I just noticed that single newline (`\n`) characters are seemingly ignored in `cli_abort` but double newlines (`\n\n`) are respected.

1. Is this expected behaviour?
2. What is the recommended way to insert a single linebreak into a `cli_abort`  error message?

Reprex (using version `cli_3.5.0`) :

``` r
library(cli)

# single newline character doesn't affect error message
cli_abort("Hello\nWorld")
#> Error:
#> ! Hello World

#> Backtrace:
#>     ▆
#>  1. └─cli::cli_abort("Hello\nWorld")
#>  2.   └─rlang::abort(...)

# two next to each other lead to rendered linebream
cli_abort("Hello\n\nWorld")
#> Error:
#> ! Hello
#> 
#> World

#> Backtrace:
#>     ▆
#>  1. └─cli::cli_abort("Hello\n\nWorld")
#>  2.   └─rlang::abort(...)
```

<sup>Created on 2023-01-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
In general, you can insert line breaks with `\f`: https://cli.r-lib.org/reference/inline-markup.html#wrapping

```r
❯ stop(cli::format_error("foo\fbar"))
Error: foo
bar
```

`rlang::abort()` seems to strip the `\n` unfortunately, I am not sure why:

```r
❯ rlang::abort("foo\nbar", use_cli_format=FALSE)
Error:
! foo
bar
Run `rlang::last_error()` to see where the error occurred.

❯ rlang::abort("foo\nbar", use_cli_format=TRUE)
Error:
! foo bar
Run `rlang::last_error()` to see where the error occurred.
```

Somewhat related cli issue: #460.

**Comment by gaborcsardi** [comment]
Soon there will be much better ways to nest cli components (e.g. formatted output) into other components (e.g. bullet list).
