### ISSUE TITLE
Is cli.width an appropriate default width for rule* functions?

### ISSUE THREAD

**Issue by MilesMcBain** [r-lib/cli#56]
Editors other than RStudio have console windows that can have line truncation dynamically toggled, and can be scrolled horizontally as well as vertically. This can be utilised to set a large value for the `cli.width` option and have R output print without columns getting moved onto new lines or getting removed altogether (like with Tibbles).

Using this setting creates an annoyance though with packages that use the `cli::rule` function since they may print many thousands of useless `-` or `=` characters to the console. E.g.

![cli_rule](https://user-images.githubusercontent.com/9996346/46184862-d4b50800-c31a-11e8-9eb6-4e04fc019c03.png)

Could `console_width()` look for some other option in preference to `cli.width`? maybe `cli.visible.width` or `rule.width`?

Edit: The major annoyance actually comes in running `testthat`, where the frequent use of `rule` in the output seems to slow everything down.

**Comment by MilesMcBain** [comment]
PS. I think I should be able to manage a PR if you agree.

**Comment by gaborcsardi** [comment]
Hmmm, I get the idea, but I think it is hard to design cli output if the windows can have an infinite width. E.g. I want to show a list of packages, like in https://github.com/r-lib/cliapp/blob/master/inst/scripts/search.R which looks like this:
```
❯ ./search.R  command line
ℹ Searching...
✔ Found 60 packages in 23ms

1. optparse 1.6.0 -- Command Line Option Parser

  A command line parser inspired by Python's 'optparse' library to be used with
  Rscript to write "#!" shebang scripts that accept short and long
  flag/options.

  3 months ago by Trevor L Davis <trevor.l.davis@gmail.com>

2. colt 0.1.1 -- Command-Line Color Themes

  A collection of command-line color styles based on the 'crayon' package.
  'Colt' styles are defined in themes that can easily be switched, to ensure
  command line output looks nice on dark as well as light consoles.

  about a year ago by Stefan Fleck <stefan.b.fleck@gmail.com>

[...]
```

cliapp uses `cli.width` to wrap the description here. It does not seem very nice to show the package description in one long line here, does it? In other words, I don't really see that rules are _that_ special that they need an option. Quite often you want to cut/wrap everything at `cli.width`, I think.

I see the use case for tibbles (and tables in general?), though, so maybe it is better to go the other way and have a `tibble.width` option. Assuming there isn't one already.
