### ISSUE TITLE
`.file` format makes the rest of the string disappear with very long file names

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/cli#560]
Here is a reprex :
```r
#works with short names
cli::cli_inform("Unzipping {.file C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.zip}")
#doesn't with long names
cli::cli_inform("Unzipping {.file C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxx xxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxxxxxxxxxx xxxxxxxxxxxx xxxxxxxx.zip}")
#works with .val
cli::cli_inform("Unzipping {.val C:\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxxxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxx xxxxxx\\xxxxx xxxxx\\xxxxxxxxxx\\xxxxxxxxxxx xxxxxxxxxxxx xxxxxxxx.zip}")
```
![image](https://user-images.githubusercontent.com/15105152/211053042-7fbbee98-e2c4-46aa-84fb-26559a001b19.png)

This seems to pertain to console width. 
This screenshot was taken with `getOption("width")==86`, but when I stretch my console until `getOption("width")==193`, the problem disappears and "Unzipping" comes back. 
With `reprex::reprex(),`, everything works as expected (hence the screenshot) although `getOption("width")==80`.

**Comment by gaborcsardi** [comment]
Seems like an issue with RStudio only, reported here: https://github.com/rstudio/rstudio/issues/13869
