### ISSUE TITLE
`cli_h*()` and newlines

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/cli#563]
Perhaps I am not understanding something, but the use of newlines for h1 & h2 *seems* switched. I would expect more spacing for h1 and less for h2:

``` r
library("cli")

cli_h1("Header {.emph 1}")
#> 
#> ── Header 1 ────────────────────────────────────────────────────────────────────
cli_h2("Header {.emph 2}")
#> 
#> ── Header 2 ──
#> 
cli_h3("Header {.emph 3}")
#> ── Header 3
```

<sup>Created on 2023-01-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

If this is not intended, I'd be happy to make a PR, if you would point me towards code that sets the formatting (I had a quick look and couldn't find it).

Thanks!

**Comment by ijlyttle** [comment]
When call these from a function, rather than from the R prompt, I see a consistent, single newline above each heading, so I don't know that this is actually a problem or not.

Please don't hesitate to close, as you have more than enough *actual* problems in front of you :)

**Comment by gaborcsardi** [comment]
I am afraid that this is the default theme: https://github.com/r-lib/cli/blob/3de7ad6195ed8e6d8e56ec5edd6c9acfb718f981/R/themes.R#L102

```r
    h1 = list(
      "font-weight" = "bold",
      "margin-top" = 1,
      "margin-bottom" = 0,
      fmt = function(x) cli::rule(x, line_col = "cyan")),
    h2 = list(
      "font-weight" = "bold",
      "margin-top" = 1,
      "margin-bottom" = 1,
      fmt = function(x) paste0(symbol$line, symbol$line, " ", x, " ",
                               symbol$line, symbol$line)),
    h3 = list(
      "margin-top" = 1,
      fmt = function(x) paste0(symbol$line, symbol$line, " ", x, " ")),
```

The logic being that h1 has a rule, which is distinctive enough, so no whitespace is needed.

**Comment by ijlyttle** [comment]
Fair enough - given this is the design intent, not an issue from my perspective.

Thanks for indulging me!
