### ISSUE TITLE
`pb_spin` not found

### ISSUE THREAD

**Issue by mgirlich** [r-lib/cli#566]
I noticed a couple of issues when I tried to adapt the format of the progress bar:

* it would be nice if things like `pb_spin` are found without attaching cli
* the chained error doesn't need to mention `eval(expr, envir = envir)`
* The `Error in "\"id\" %in% names(args)"` only appears when doing the reprex

``` r
cli::cli_progress_bar(
  format = "{pb_spin}",
  total = length(letters)
)
for (letter in letters) {
  cli::cli_progress_update()
  Sys.sleep(5/10)
}
#> Error in "\"id\" %in% names(args)": ! Could not evaluate cli `{}` expression: `pb_spin`.
#> Caused by error in `eval(expr, envir = envir)`:
#> ! object 'pb_spin' not found
```

Error message when not run in a reprex has two `!`:

```r
Error:
! ! Could not evaluate cli `{}` expression: `pb_spin`.
Caused by error in `eval(expr, envir = envir)`:
! object 'pb_spin' not found
```

<sup>Created on 2023-01-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
You need to use `cli::pb_spin`.

```r
cli::cli_progress_bar(
  format = "{cli::pb_spin}",
  total = length(letters)
)
for (letter in letters) {
  cli::cli_progress_update()
  Sys.sleep(5/10)
}
```
