### ISSUE TITLE
`ansi_collapse()` with length-2 input

### ISSUE THREAD

**Issue by salim-b** [r-lib/cli#568]
I really appreciate the recently introduced function [`ansi_collapse()`](https://cli.r-lib.org/reference/ansi_collapse.html). It's more powerful than the other existing alternatives I know of, [`stringr::str_flatten_comma()`](https://stringr.tidyverse.org/reference/str_flatten.html) and [`knitr::combine_words()`](https://rdrr.io/cran/knitr/man/combine_words.html).

The only downside: `ansi_collapse()` currently has no means to use different separators for length-2 and longer inputs.

This is relevant when someone wants to collapse a vector of elements with [**serial comma**](https://en.wikipedia.org/wiki/Serial_comma) (aka "Oxford comma"), which the default args of `ansi_collapse()` seem to target but don't quite arrive at[^1]:

``` r
cli::ansi_collapse(letters[1])
#> [1] "a"
cli::ansi_collapse(letters[1:2])
#> [1] "a, and b"
cli::ansi_collapse(letters[1:3])
#> [1] "a, b, and c"
```

<sup>Created on 2023-01-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

For proper serial-comma-style, the second expression above should yield `"a and b"` instead (i.e. no comma). This could be supported via an additional param `single` to specify a *third* separator string for length-2 inputs (which are gonna be separated by a *single* separator). The default value could be `single = " and "`.

What do you think?

[^1]: `knitr::combine_words()` supports this common case via its param `oxford_comma`

**Comment by gaborcsardi** [comment]
We can have a `sep2` argument, used if `length() == 2`, and defaulting to `" and "`. Is that good?

**Comment by salim-b** [comment]
That is also fine! 👍

**Comment by gaborcsardi** [comment]
A PR is welcome. :) But no pressure. :)

**Comment by salim-b** [comment]
I've looked into it. This beast was way more complex internally than anticipated, but I think #569 should work.
