### ISSUE TITLE
The documentation for no() says 'see examples below', but there are no examples

### ISSUE THREAD

**Issue by mpjashby** [r-lib/cli#576]
https://github.com/r-lib/cli/blob/01f932adafd58a59d596b745bf88359c5cb5a969/R/pluralize.R#L24

**Comment by gaborcsardi** [comment]
Ooops, thanks for letting us know. There are some examples in this article: https://cli.r-lib.org/reference/pluralization.html#use-no-instead-of-zero

Would you like to submit a PR to add some examples to the manual page? They can be the same examples. No pressure, of course. :)
