### ISSUE TITLE
Disable urls during `Rmarkdown::render()` in RStudio?

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#581]
e.g. create an `.Rmd` containing this code and render it with cmd + shift + K

````
```{r}
cli::cli_abort("{.url https://posit.co}")
```
````

The issues panes doesn't support ANSI formatting:

<img width="444" alt="Screenshot 2023-02-08 at 12 54 52" src="https://user-images.githubusercontent.com/4196/217625391-6ad223bb-ff1c-426e-b71e-377e3b204269.png">

OTOH the output pane does:

<img width="445" alt="Screenshot 2023-02-08 at 12 55 14" src="https://user-images.githubusercontent.com/4196/217625440-049d48dd-0714-4428-81f4-c34b3759f505.png">

**Comment by gaborcsardi** [comment]
Since the same output goes to both places we can either have no links anywhere, or maybe we can add links support to the issues panel, or at least make the issue panel drop ANSI sequences?

**Comment by hadley** [comment]
I think no links might be the safer choice.

**Comment by cderv** [comment]
@mikeroswell beat me to it while I was writing this message. Here it is anyway 

We have an occurence of this in https://github.com/yihui/knitr/issues/2234 with **dplyr** deprecation warnings as **lifecycle** is using urls now in the deprecation message 

For HTML outputs, it just show undesired character in the message, but for PDF, it prevents rendering because of those unknown special characters still present.

**Comment by hadley** [comment]
Looking at the issue from knitr, that might be actually be a different problem? Because there the escapes are appearing in the document.

**Comment by gaborcsardi** [comment]
I think they should be the same, the R process that runs knitr runs "in the render pane", so hyperlinks were turned on. Now they are off.

**Comment by hadley** [comment]
I thought we used different heuristics inside an Rmd, but maybe I'm imagining that?

**Comment by gaborcsardi** [comment]
We are doing that for colors, yeah. Probably the simplest is that if there are no colors, then we also turn off the hyperlinks.

**Comment by gaborcsardi** [comment]
It is already fixed.

**Comment by pg320** [comment]
Could you guide me on installing the package from GitHub? I've tried using the devtools and remotes package, but they fail as cli is already in ise

**Comment by gaborcsardi** [comment]
Try this:

```r
install.packages("pak", repos = sprintf(
  "https://r-lib.github.io/p/pak/stable/%s/%s/%s",
  .Platform$pkgType,
  R.Version()$os,
  R.Version()$arch
))
pak::pkg_install(r-lib/cli)
```

**Comment by mikeroswell** [comment]
with quotes around the package name, `pak::pkg_install("r-lib/cli")`
-Michael

**Comment by jennybc** [comment]
Just to add more color, the change motivated by this seems to have also fixed a problem in `devtools::build_rmd()`, where I was seeing ANSI escapes in the rendered product.
