### ISSUE TITLE
Unable to update package cli

### ISSUE THREAD

**Issue by fdcabfer** [r-lib/cli#584]
Hi,

Whenever I try to update the package "cli" I get the following message:

Error in install.packages : Updating loaded packages

Then I'm asked to restart session in R. If I choose no, nothing happens. If I choose yes, I only get the message "Restarting R session..." and then the same first error. After restarting for the second time, I get a fatal error and R shuts down.

Is there a way for me to update this package? I need it because in one of my codes I'm loading the tidyverse library (library(tidyverse)) and I get the following error:

Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘cli’ 3.4.0 is already loaded, but >= 3.4.1 is required

So it seems that I need to update cli before installing tidyverse, but so far I'm unable to update cli because of this problem.

Can someone help me?

Thanks,

Federico Caballero

**Comment by gaborcsardi** [comment]
What's your OS? Do you use an IDE? Are any packages loaded when you are trying to update?

In any case, I suggest you install pak, and try to update with that, it goes like this:
```r
install.packages("pak", repos = sprintf(
  "https://r-lib.github.io/p/pak/stable/%s/%s/%s",
  .Platform$pkgType,
  R.Version()$os,
  R.Version()$arch
))

pak::pkg_install("cli")
```

**Comment by fdcabfer** [comment]
Thank you @gaborcsardi , it works now! Thank you so much for your help :-)
