### ISSUE TITLE
Inline markup is not described in ?cli_abort

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/cli#585]
I am trying to figure out how to write a cli_abort() message for a PR to a repo using cli, but I couldn't figure out what the `{.name expr}` entries mean, precisely, from reading [`?cli_abort`](https://cli.r-lib.org/reference/cli_abort.html).

The page mentions "inline styling" in passing but doesn't offer the reader any links for further reading.

"glue substitutions" are mentioned but this is a supplementary markup beyond out-of-the-blox `glue` AFAIK.

`message=`, where the interpretation is happening, points to [`?cli_bullets`](https://cli.r-lib.org/reference/cli_bullets.html), but there's no mention at all on that page.

Only through some 🕵️ work did I find related issue https://github.com/r-lib/cli/issues/502 here which points to [this exposition](https://cli.r-lib.org/reference/inline-markup.html?q=quote#collapsing-inline-vectors).

Should that be linked directly from `cli_abort()` and/or `cli_bullets()` as well?

**Comment by gaborcsardi** [comment]
OTOH, that means that it needs to be linked from `cli_text()`, etc. many cli functions. 

And the inline markup manual page is the first one in the reference: https://cli.r-lib.org/reference/index.html#semantic-cli-elements and the reference also links to the intro vignette, which is the document that new users would read, ideally.

**Comment by gaborcsardi** [comment]
For the record, there is definitely downside having too many links in a manual page.
Linking to all other manual pages within the package is just as bad as linking to none of them.

I also don't think that it is far-fetched to expect the user to look at the manual of the package if they don't understand something.

This said, we can link to the inline markup manual page, and a couple of others from the functions' pages. I'll do this now.

**Comment by MichaelChirico** [comment]
Do all the pages point to cli_bullets? cli_abort per se didn't need it, but it pointed to that page and I expected to find something there.

if there are a few shared pages that are pointed to like that it would also have fit my use case.

it's just odd for such a key piece of the package to be undiscoverable from a dead end landing page like that.

**Comment by MichaelChirico** [comment]
Much thanks for this! :raised_hands:
