### ISSUE TITLE
`.fun` or `.fn`?

### ISSUE THREAD

**Issue by eitsupi** [r-lib/cli#597]
The explanation in the article seems to be confused as to whether `.fun` or `.fn`.

https://github.com/r-lib/cli/blob/c37f34be35d30e776d768509a38f1e5f710aab0d/R/cliapp-docs.R#L61-L64
https://github.com/r-lib/cli/blob/c37f34be35d30e776d768509a38f1e5f710aab0d/R/cliapp-docs.R#L107

**Comment by gaborcsardi** [comment]
Either one works.
