### ISSUE TITLE
Support dashes/rules?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/cli#60]
- [ ] Figure dash
- [ ] En-dash
- [ ] Em-dash
- [ ] ...?

https://en.wikipedia.org/wiki/Dash

**Comment by gaborcsardi** [comment]
So, I added these, but it seems that for fix-width fonts, they all look the same
![Screen Shot 2019-03-15 at 4 58 29 PM](https://user-images.githubusercontent.com/660288/54448439-a9e13380-4743-11e9-834d-c41c32b67cc2.png)
