### ISSUE TITLE
Bottleneck when printing ansi colors in RStudio

### ISSUE THREAD

**Issue by wlandau** [r-lib/cli#607]
With https://github.com/r-lib/cli/commit/778f7d053a7901d1e9ea17cd6b6905b16217177a on Mac OS, `system.time(replicate(1e3, print(cli::col_green)))` completes in 0.125 seconds in the terminal and 3.384 seconds in the RStudio IDE. For the RStudio case, flame graphs with [proffer](https://r-prof.github.io/proffer) seem to point to `num_ansi_colors()`, (mainly via `rstudio$detect()` and `utils::readCitationFile()`) as the main source of overhead (see below). For packages like [`targets`](https://docs.ropensci.org/targets/), this overhead is noticeable because some projects generate a lot of messages.

Would it be possible for `cli` to pre-compute/cache the output of `cli::num_ansi_colors()` (maybe on load)? Unless I am missing something, it does not seem like ansi color data would change from R session to R session.

![cli](https://github.com/r-lib/cli/assets/1580860/b048b530-3cf3-4f5f-a546-6af633bebbd6)

**Comment by gaborcsardi** [comment]
No, it is not possible to precompute it, because it might change, e.g. the can set an option, call `sink()`, etc. 

However, if you know that it does not change, then you can cache it yourself. E.g. in the terminal:
```
❯ system.time(replicate(1e3, cli::col_green("foo")))
   user  system elapsed
  0.040   0.000   0.041

❯ options(cli.num_colors = cli::num_ansi_colors())
❯ system.time(replicate(1e3, cli::col_green("foo")))
   user  system elapsed
  0.009   0.000   0.009
```

And in RStudio:
```
> system.time(replicate(1e3, cli::col_green("foo")))
   user  system elapsed 
  0.903   0.149   1.053 
> options(cli.num_colors = cli::num_ansi_colors())
> system.time(replicate(1e3, cli::col_green("foo")))
   user  system elapsed 
  0.008   0.000   0.008 
```

**Comment by wlandau** [comment]
Thanks for explaining, that helps. Now that I know what to look for, I also see there is a `cli.unicode` option (for onlookers, c.f. https://github.com/r-lib/cli/issues/396).
