### ISSUE TITLE
Please remove Menlo-Regular.ttf

### ISSUE THREAD

**Issue by QuLogic** [r-lib/cli#61]
I cannot find any _official_ source or license for Menlo Regular, and as far as I can tell, it's only available in Apple products. There is no license tag in the file itself, so I can only assume it is _not_ redistributable.

At best, I can see that some think it's derived from Bitstream Vera Sans, but as its license is not copyleft, there's no reason to assume Menlo is under any similar license.

**Comment by QuLogic** [comment]
At best, I can find [this conversation](https://sourceforge.net/p/dejavu/mailman/dejavu-fonts/thread/447C98F6-DEF9-43D6-9746-D0B7CEEEE7D9%40zone38.net/#msg23429375) on the DejaVu mailing list, for which Menlo is assumed to be proprietary.

**Comment by gaborcsardi** [comment]
Well, even if it is proprietary, given that it is available for download from _a lot_ of different places, I think it is really doubtful that Apple would want to enforce its copyright.

Some of its derivatives are even available under an open source license, e.g. https://github.com/andreberg/Meslo-Font#license

Anyway, it does make the package bigger, so it makes sense to remove it.

**Comment by gaborcsardi** [comment]
I removed it from the R package, I think keeping it in the repo is fine.
