### ISSUE TITLE
progress bar output being included in RMarkdown output

### ISSUE THREAD

**Issue by francisbarton** [r-lib/cli#616]
I get progress bar output included when knitting Rmd:

![image](https://github.com/r-lib/cli/assets/1819920/a9d79bb2-291f-4b06-a357-f66e639b1c48)

This occurs if I have `.progress = rlang::is_interactive()` set within the calling `map` function. I thought knitting Rmd would count as non-interactive.

I think this is the same issue as Hadley is referring to in #583 but I'm not sure.

**Comment by gaborcsardi** [comment]
> This occurs if I have `.progress = rlang::is_interactive()` set within the calling map function. I thought knitting Rmd would count as non-interactive.

Which means that this can only be addressed in `rlang::is_interactive()`, no? cli only receives `.progress = TRUE`, so that's what it does.
