### ISSUE TITLE
FR: Send cli output to the RStudio Viewer or build pane

### ISSUE THREAD

**Issue by olivroy** [r-lib/cli#618]
Is it possible to send cli output to the viewer pane in RStudio?

With cli hyperlinks that work? or would that be only possibly on RStudio's side?

Edit: Other possiblity, would it be possible to write custom output to the build pane, like testthat, devtools, or check?

**Comment by gaborcsardi** [comment]
I don't think this is up to cli, but it is up to RStudio. You can capture the output of cli, and then send it to RStudio (if that's possible), like normal non-cli text.

(IDK of any way of writing to the build pane, and the only way I know of for writing to the viewer pane is `rstudioapi::viewer()`.
