### ISSUE TITLE
Eventually use `rstudioapi::getMode()` once it is available

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/cli#621]
https://github.com/r-lib/lifecycle/issues/167 revealed that lifecycle signaling is slow due to cli eventually calling `rstudioapi::getVersion()` and `rstudioapi::versionInfo()$mode`.

I've made a request for `rstudioapi::getMode()`, which should be _massively_ faster than `versionInfo()$mode`
https://github.com/rstudio/rstudioapi/issues/280

If that is implemented and lands on CRAN, cli should use that here:
https://github.com/r-lib/cli/blob/7eb56ebc4c315ecfef74148881b15a522c8946bf/R/aab-rstudio-detect.R#L35-L36

https://github.com/rstudio/rstudioapi/issues/279 should also make `getVersion()` much faster too.

So there is nothing actionable for cli currently, but I wanted to have this issue so we don't forget to update this

**Comment by JohannesFriedrich** [comment]
What´s the current status for the different packages `cli`, `rstudioapi`and `lifecycle` concerning this issue? I have big performance problems in my code because of the repeated call of `utils::readCitationFile()`, as mentioned [here](https://github.com/r-lib/lifecycle/issues/167)
