### ISSUE TITLE
Truncating silently markup in RStudio when string ends with markup.

### ISSUE THREAD

**Issue by olivroy** [r-lib/cli#627]
Possibly the string widths are not correctly assessed?, 

Output of my RStudio console
![image](https://github.com/r-lib/cli/assets/52606734/a0ace63f-2b1f-435b-8ac2-bb461e7360bd)

Expected (works when cli.width >= 68.) i.e. if your console width is wider than 68 when not setting options.
![image](https://github.com/r-lib/cli/assets/52606734/7612fb06-9a42-4e57-b56e-3d0f1924ef49)

because it seems to work as expected in the reprex
``` r
to_print <- "A long {.val value} with a {.href [link](https://github.com)} with other stuff like {.help cli::inline-markup}"
options(cli.width = 35)
cli::cli_bullets(to_print)
#> A long "value" with a link
#> (<https://github.com>) with other
#> stuff like `?cli::inline-markup()`
```

<sup>Created on 2023-08-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Related to #578, because I first encountered this behaviour at startup, but this seems like a different issue.

Note: I used `options(cli.width)` here for reproducibility purpose only, but I am trying to recreate the behavior when not setting options.

Let me know if I can provide more info. (I am still on an older RStudio version 2023.06.1, but I don't think this has been changed recently.)

* This seems related to console width, because when the console is wide enough, this doesn't seem to occur.

**Comment by olivroy** [comment]
@gaborcsardi I tried creating a failing test for that, but could not see what was wrong. I am only able to reproduce in RStudio interactively.

I tried the following. but the snapshot looks fine, but does not reflect the interactive behavior.

```r
  expect_snapshot({
    withr::local_envvar(
      R_CLI_HYPERLINKS = "true",
      R_CLI_HYPERLINK_RUN = "true"
    )
    rlang::local_interactive()
    withr::local_options(cli.unicode = TRUE)
    withr::local_options(cli.num.color = 256L)
    withr::local_options(cli.width = 25)
    cli_text("A {.val veryaaaaa} long hyperlink {.href [text](https://github.com)}")
  }

  )
```

**Comment by olivroy** [comment]
Hi @gaborcsardi, do you think this is a cli or RStudio issue? Do you think it will be fixed by https://github.com/rstudio/rstudio/issues/13869. If so, maybe mention it for QA.

**Comment by gaborcsardi** [comment]
Does it happen outside of RStudio? E.g. in a (non-RStudio) terminal?

**Comment by olivroy** [comment]
Doesn't seem like it. (although I don't have a terminal that supports links)

Are you able to see this behavior with this reprex?

```
to_print <- "A long {.val value} with a {.href [link](https://github.com)} with other stuff like {.help cli::inline-markup}"
options(cli.width = 35)
cli::cli_bullets(to_print)

```

**Comment by gaborcsardi** [comment]
It works ina terminal. It is probably this issue: #560, already reported to RStudio.
