### ISSUE TITLE
Possibility to create new inline markup?

### ISSUE THREAD

**Issue by olivroy** [r-lib/cli#629]
Is it possible to extend inline markup?

I have something in mind like

```r
{.issue r-lib/cli#628}
# a shortcut for typing
{.href [r-lib/cli#628](https://github.com/r-lib/cli/issues/628)}
```

**Comment by gaborcsardi** [comment]
Sure, see how the built-in ones are created in `themes.R`. OTOH this is not very convenient in a package because there is no good way to create package specific themes.

**Comment by olivroy** [comment]
Thanks!
