### ISSUE TITLE
palettes vignette lacks context

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/cli#632]
I am trying to move some simple code using {crayon} to use {cli} instead and poking around on the CLI website for intro vignettes.

I clicked into the [palettes vignette](https://cli.r-lib.org/articles/palettes.html) -- it looks nice but as a beginner I have no idea how to use the info presented there.

Some links out at the top would help -- either pointing to other vignettes or linking help pages where the palettes are relevant.

**Comment by gaborcsardi** [comment]
I guess it should link here: https://cli.r-lib.org/reference/ansi_palettes.html?q=palette#details ?
