### ISSUE TITLE
pagedown out of date

### ISSUE THREAD

**Issue by asadow** [r-lib/cli#638]
I was going to propose changes to `usethis-ui.Rmd` (adding `c()` inside `cli_fnc(message, "i" = )`, but I noticed these changes were already implemented. Yet the site is not reflecting them. [See this page on "formatted using `cli_bullets()`"](https://cli.r-lib.org/articles/usethis-ui.html).

**Comment by gaborcsardi** [comment]
Did you check the docs for the dev version at https://cli.r-lib.org/dev/?

**Comment by asadow** [comment]
I was unaware there was a dev page. Thank you.
