### ISSUE TITLE
Add option to customize last separator when auto-collapsing character vectors

### ISSUE THREAD

**Issue by Teebusch** [r-lib/cli#639]
`cli_text()` and `pluralize()` auto-collapse character vectors, but there is no option to configure the final separator "and":

```r
pkgs <- c("pkg1", "pkg2", "pkg3")
cli_text("Will remove the {.pkg {pkgs}} package{?s}.")
```
```r
#> Will remove the pkg1, pkg2, and pkg3 packages.
```
This is hardcoded as `last` in `cli:::inline_collapse()`:

```r 
function (x, style = list()) 
{
  sep <- style[["vec-sep"]] %||% style[["vec_sep"]] %||% ", "
  if (length(x) >= 3) {
    last <- style[["vec-last"]] %||% style[["vec_last"]] %||% 
      ", and "
  }
  else {
    last <- style[["vec-sep2"]] %||% style[["vec_sep2"]] %||% 
      style[["vec-last"]] %||% style[["vec_last"]] %||% 
      " and "
  }
  trunc <- style[["vec-trunc"]] %||% style[["vec_trunc"]] %||% 
    20L
  col_style <- style[["vec-trunc-style"]] %||% "both-ends"
  ansi_collapse(x, sep = sep, last = last, trunc = trunc, 
    style = col_style)
}
```

It would be useful to expose a `last` argument to the user so they can override it with a language-specific separator or just a regular ','. 

A usable workaround is to collapse the character vector outside of the function, e.g. with `glue::collapse()`, which does have a `last` argument.

**Comment by gaborcsardi** [comment]
There are several ways to do this, here are two:
```r
❯ cli_text("foo {.or {letters[1:5]}} bar")
foo a, b, c, d, or e bar
```

```r
❯ v <- cli_vec(letters[1:5], style = list("vec-last" =  ", or "))
❯ cli_text("foo {v} bar")
foo a, b, c, d, or e bar
```

**Comment by Teebusch** [comment]
Awesome! Thanks for the quick response! It might be worth adding to the relevant documentation article https://cli.r-lib.org/articles/pluralization.html#use-the-length-of-character-vectors

**Comment by gaborcsardi** [comment]
> Also worth mentioning that the first solution you suggest only is a solution if you want to replace "and" with "or"

You would need define `{.und}`.

> And the second solution means you won't have the convenience of the automatic character vector collapsing.

I am not sure what you mean, see my second example. In general, you either need to define your own class with a theme, or add the style to the vector that you want to collapse.

**Comment by Teebusch** [comment]
I ran into this issue again today and it took me a while to remember how to define a custom `{.und}` inline markup again.
For future me and anyone else who might need it: Here are two ways to do it:

```r
x <- c("a", "b", "c")
text <- "{.und {x}}"
my_theme <- list(span.und = list("vec-sep2" = " und ", "vec-last" = ", und "))

# -- option 1: modify theme temporarily for a single div

cli::cli_div(theme = my_theme)
cli::cli_text(text)
cli::cli_end()

# > a, b, und c

# -- modify theme more permanently via user theme

options("cli.user_theme" = my_theme)
cli::cli_text(text)

# > a, b, und c
```

### Relevant sources

https://cli.r-lib.org/reference/inline-markup.html#collapsing-inline-vectors
https://github.com/r-lib/cli/blob/2ddcc1af364cf6737a06cec8a344a52b26dd9afa/R/themes.R#L254
https://cli.r-lib.org/reference/themes.html
https://cli.r-lib.org/reference/cli_div.html
https://cli.r-lib.org/reference/inline-markup.html
