### ISSUE TITLE
Progress bar for `furrr::future_map` and `future.apply::future_lapply` functions

### ISSUE THREAD

**Issue by Mark-AP** [r-lib/cli#653]
I know that the function cli_progress_along is experimental. I ran the code below got a progress bar showing while updating me as my code ran until completion.

`lapply_res <- lapply(cli_progress_along(x), fun)`

I tried switch the lapply in favor for future_lapply/future_map but no progress bar is generated when testing out these functions

`fl_res <- future_lapply(cli_progress_along(x), fun)`
`fm_res <- future_map(cli_progress_along(x), fun)`

**Comment by gaborcsardi** [comment]
I am fairly sure that it is not possible to make`progress_along` work with future, I am afraid.
