### ISSUE TITLE
cli::pb_current_name

### ISSUE THREAD

**Issue by tvedebrink** [r-lib/cli#655]
Would it be possible to add an option to print the name of the current element if provided?

I have a made an example in `purrr` where the name is fetched from an external vector:

```{r}
mtcars_cyl <- mtcars %>% split(.$cyl)

mtcars_cyl_names <- mtcars_cyl %>% names()

mtcars_cyl %>% 
  map_int(~ {
    Sys.sleep(1)
    .x %>% nrow()
  }, .progress = list(format = "{cli::pb_bar} [Cyl: {mtcars_cyl_names[{cli::pb_current}]}]", clear = FALSE)
  )
■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■  [Cyl: 8]
 4  6  8 
11  7 14 
```
Thanks for your help in advance!

**Comment by gaborcsardi** [comment]
This is something that would need fixing in purrr I am afraid, because purrr knows about the vectors it is iterating over, cli does not.

But I am not even sure what the best practice is to iterate over a named vector in purrr.

**Comment by tvedebrink** [comment]
I just realised that the `extra` argument can be used to solve this 👍 
```{r}
mtcars %>% 
  split(.$cyl) %>% 
  map_int(~ {
    Sys.sleep(1)
    .x %>% nrow()
  }, 
  .progress = list(format = "{cli::pb_bar} [Cyl: {cli::pb_extra$nms[{cli::pb_current}]}]", clear = FALSE, extra = list(nms = names(.)))
)
```
Once again thanks for the excellent package!
