### ISSUE TITLE
Move usethis::ui_*() functions to this package

### ISSUE THREAD

**Issue by jennybc** [r-lib/cli#68]
That is the plan, right?

@Hadley @gaborcsardi

**Comment by jennybc** [comment]
![cli-planning](https://user-images.githubusercontent.com/599454/58119849-f6c50880-7bd1-11e9-9ba4-ccd0a2b6a4ad.jpg)

**Comment by gaborcsardi** [comment]
There is now a "transition guide" that covers most of this: https://cli.r-lib.org/dev/articles/usethis-ui.html
