### ISSUE TITLE
Creating tables or boxes with multiple rows/columns

### ISSUE THREAD

**Issue by MLopez-Ibanez** [r-lib/cli#69]
Our package (https://cran.r-project.org/package=irace) would like to use cli to replace/prettify code such as:

```r
cat(sep = "", 
+-+-----------+-----------+-----------+---------------+-----------+--------+-----+----+------+
| |   Instance|      Alive|       Best|      Mean best| Exp so far|  W time|  rho|KenW|  Qvar|
+-+-----------+-----------+-----------+---------------+-----------+--------+-----+----+------+")
```

that is, tables with multiple rows and columns.

Is this within the scope of the cli package?

**Comment by gaborcsardi** [comment]
I would say, it is borderline wrt to scope, but this is not trivial to implement, and we don't have any plans to do it.
