### ISSUE TITLE
Pluralisation fails for infinite values

### ISSUE THREAD

**Issue by eliocamp** [r-lib/cli#701]
If the number used for pluralisation is `Inf`, message creation fails. 

``` r
errormsg <- "{n_out} file{?s} expected"

n_out <- 1
cli::cli_text(errormsg)
#> 1 file expected

n_out <- 2
cli::cli_text(errormsg)
#> 2 files expected

n_out <- Inf
cli::cli_text(errormsg)
#> Warning in make_quantity(values$qty): NAs introduced by coercion to integer
#> range
#> Warning in make_quantity(values$qty): NAs introduced by coercion to integer
#> range
#> Error in if (qty != 1) parts[1] else "": missing value where TRUE/FALSE needed
```

The issue I think starts [here](https://github.com/r-lib/cli/blob/d9febb5860083e6d028da42d5f6a3888754c798d/R/pluralize.R#L12C1-L12C23), where the number is coerced to an integer. `as.integer(Inf)` is NA. Then [here](https://github.com/r-lib/cli/blob/d9febb5860083e6d028da42d5f6a3888754c798d/R/pluralize.R#L90C4-L90C35) `process_plural()` runs `if (length(parts) == 1)`, which is `NA`. 

I'm not sure there's a standard way of pluralising infinite value, so the solution might be to catch the issue early and throw a better error instead of implementing plurals for `Inf`.

**Comment by gaborcsardi** [comment]
Closed by #716.
