### ISSUE TITLE
`{.run ...}` will not allow a custom function to be clickable if its name contains a `.`

### ISSUE THREAD

**Issue by DesiQuintans** [r-lib/cli#705]
I made a test package (<https://github.com/DesiQuintans/testclirun>) to illustrate the point, but this bug report is pretty simple.

My package has two functions: `testclirun::testView()` and `testclirun::test.View()`. They take no arguments and are the same object, one simply has a dot in the name (i.e. `test.View <- testView`).

Using the formatting `{.run testclirun::testView()}` produces a clickable link in RStudio.

Using the formatting `{.run testclirun::test.View()}` **makes an unclickable link**. 

![image](https://github.com/user-attachments/assets/43a90cb6-5b4d-44ff-8761-5491683bb57b)

![image](https://github.com/user-attachments/assets/35b0fa89-f84e-4fe2-9ffb-d525d8472b2a)

It is probably colliding with the use of `.` in the formatting tags, but the problem is not mentioned in <https://cli.r-lib.org/reference/links.html>.

**Comment by gaborcsardi** [comment]
This works for me in a terminal, so it is probably a restriction in RStudio.

<img width="903" alt="Screenshot 2024-07-31 at 9 15 59 AM" src="https://github.com/user-attachments/assets/0dd7379b-e773-4996-b2b3-2e4435d6b4ad">
