### ISSUE TITLE
cli_alter_* with cat(), symbols positioned at end of output

### ISSUE THREAD

**Issue by eli-daniels** [r-lib/cli#707]
Hello,
Thanks for a very cool package! I ran into this issue when combining cat() with cli_alert_* functions.

I would have expected the ouputs of following two code chunks to be the same:

```r
> cli::cli_alert_danger('hello you')
✖ hello you
```

```r
> cli::cli_alert_danger(cat( 'hello',  'you' ))
hello you✖ 
```
But the ✖ is in the wrong position in the second case.

**Comment by gaborcsardi** [comment]
I am not sure why you expected that. `cat()` prints the text and returns `NULL` before `cli::cli_alert_danger()` is even called. So I am not sure how `cli_alert_danger()` could do anything differently here. 

```
❯ print(cat( 'hello',  'you' ))
hello youNULL
```

**Comment by eli-daniels** [comment]
Okay, I probably just don't really understand what `cat()` does. I'm getting my intended output by replacing it with `paste()`.
Anyway, thanks for your help!

**Comment by gaborcsardi** [comment]
`cat()` prints to the screen (by default) and does not return anything:
```r
❯ x <- cat("foo", "bar")
foo bar
❯ x
NULL
```

**Comment by eli-daniels** [comment]
Right, so the strings are printed directly to console by `cat()` which returns NULL to `cli_alert_*` which only then prints the symbol. Got it, thanks!
