### ISSUE TITLE
How do you use the stdout stream instead of the stderr stream

### ISSUE THREAD

**Issue by mattfidler** [r-lib/cli#71]
I'm wondering how you use the stdout stream instead of the stderr stream with cli.  I have print functions that use cli, and would like them to use stdout instead of stderr.

**Comment by gaborcsardi** [comment]
Fixed in 46fdf54c0a7ecfccd44f15820a5e70051466b996

We now have a function to create print methods. Also, in interactive sessions cli prints to the standard output now.

**Comment by mattfidler** [comment]
Thanks
