### ISSUE TITLE
`col_grey()` and `col_silver()` is unreadable in Positron (Tomorrow Night Blue theme)

### ISSUE THREAD

**Issue by olivroy** [r-lib/cli#711]
![image](https://github.com/user-attachments/assets/b5878790-f753-43fa-80b8-bdd4e8756469)

You are supposed to read xxx from there.

In RStudio, it is 
![image](https://github.com/user-attachments/assets/59af88c7-63a6-41d2-81f7-b1772a0ebc97)

I am saying this because the `last_trace()` message from rlang seems to use this.

As a comparison, the `style_subtle()` from pillar displays much better.
![image](https://github.com/user-attachments/assets/a9705681-2701-4a47-bae0-0e1e5564eff2)

```r
# this is also unreadable
sessioninfo::session_info()
```

**Comment by gaborcsardi** [comment]
That's unfortunate, but what can cli do about that? `col_grey()` emits `"\033[90mxxx\033[39m"`, the rest is out of our hands.

**Comment by olivroy** [comment]
Is this a VScode or Positron issue then?

**Comment by gaborcsardi** [comment]
IDK, possibly.

**Comment by olivroy** [comment]
Maybe `col_silver()` could emit the same as `pillar::style_subtle()` which is well handled. "\033[38;5;246mxxx\033[39m"

**Comment by gaborcsardi** [comment]
No, it cannot. It is one of the 16 built-in colors: https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit
