### ISSUE TITLE
default bullet type for abort/error is a warning

### ISSUE THREAD

**Issue by cjyetman** [r-lib/cli#713]
Out of curiosity, why is it that the default bullet type for an abort/error is a warning bullet (not a "danger" bullet) and the default bullet for a warning is no bullet?

``` r
cli::cli_alert_warning("a warning")
#> ! a warning
cli::cli_warn("a warning")
#> Warning:
#> a warning

cli::cli_alert_danger("more serious")
#> ✖ more serious
cli::cli_abort("more serious")
#> Error:
#> ! more serious
```

I realize this can be done manually, but I'd expect this to be the default:
``` r
cli::cli_alert_warning("a warning")
#> ! a warning
cli::cli_warn(c("!" = "a warning"))
#> Warning:
#> ! a warning

cli::cli_alert_danger("more serious")
#> ✖ more serious
cli::cli_abort(c("x" = "more serious"))
#> Error:
#> ✖ more serious
```

Not really arguing for this, just wondering what the logic is.

**Comment by gaborcsardi** [comment]
You are supposed to add your own bullets to `cli_warn()` etc., in any way you like.
