### ISSUE TITLE
Make the package thinner

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#73]
- [ ] make fansi optional or remove, currently only used for string wrap
- [ ] make progress optional

**Comment by gaborcsardi** [comment]
As it is now, we need fansi, and will drop progress. We also have a lot of images in the README now, maybe we'll just omit it from the package.

**Comment by hadley** [comment]
Maybe move most of the contents of the README to an article? (i.e. a vignette that's not included in the package)

**Comment by jimhester** [comment]
Or just host the images externally maybe, just setting the upload function the chunks so they upload automatically to imgur would work I guess? https://rdrr.io/cran/knitr/man/imgur_upload.html

**Comment by gaborcsardi** [comment]
The images can be on GH, e.g. https://github.com/r-lib/pak/blob/1bdd6e7a5f72fe7ea34a46f0142b3387bfa6689b/README.Rmd#L34

**Comment by jimhester** [comment]
Yeah or that, only issue is makes the cloning slower, but not a huge deal.
