### ISSUE TITLE
Integrate cat helpers

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#8]
```
cat_line <- function(..., file = "") {
  cat(..., "\n", sep = "", file = file)
}

cat_kable <- function(x, ..., file = "") {
  cat(kable(x, row.names = FALSE), sep = "\n", file = file)
  cat_line(file = file)
}

cat_header <- function(..., level = 1, file = "") {
  cat(bold(paste0(strrep("#", level), " ", ...)), "\n", sep = "", file = file)
  cat_line(file = file)
}

cat_bullet <- function(..., file = "") {
  cat_line("* ", ..., file = file)
}

cat_print <- function(x, file = "") {
  if (!identical(file, "")) {
    sink(file)
    on.exit(sink(NULL))
  }

  print(x)
}
```

**Comment by gaborcsardi** [comment]
I don't mind these, but maybe we should rename the package now?

**Comment by hadley** [comment]
What if we folded clisymbols into this package, and gave it a more general name? Maybe just cli? Then we have `cli::rule()`, `cli::symbols()` etc

**Comment by gaborcsardi** [comment]
Yeah, that would make a lot of sense.

**Comment by gaborcsardi** [comment]
Btw. what is `kable`? Which package is it coming from?

**Comment by hadley** [comment]
From knitr - it's just an easy way of getting a nice table.  But might be better to omit here since knitr is a bit dependency.

We also need `cat_rule()` and `cat_box()`
