### ISSUE TITLE
Inline string formatter

### ISSUE THREAD

**Issue by hadley** [r-lib/cli#81]
* Applies custom colour
* Call `encodeString(quote = '"')`

**Comment by gaborcsardi** [comment]
@hadley Should we call this `.val` for value?

**Comment by hadley** [comment]
Yeah — and maybe make it generic? Or at least also handle doubles by setting a smaller than usual number of digits?

**Comment by gaborcsardi** [comment]
Yeah, I think we can make it generic, should be fine.

**Comment by gaborcsardi** [comment]
So, the coloring should work via themes. Maybe the quote symbol selection should also work via themes, actually.

@hadley As for the generic and doubles, isn't there a generic that we could reuse here? It does not feel entirely right to create yet another generic for formatting various types.

**Comment by hadley** [comment]
My experience has been that formatting needs end up being very subtly different, so it's hard to reuse existing generics.

**Comment by gaborcsardi** [comment]
@hadley Right. What should be the name of the new generic then?

**Comment by gaborcsardi** [comment]
`cli_value()`?

**Comment by hadley** [comment]
`cli_format()`?
