### ISSUE TITLE
Have an inline formatter option or notation to collapse a vector, after formatting

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/cli#88]
E.g. to create a comma separated list of package names.

**Comment by gaborcsardi** [comment]
Maybe `.list` or `.lst`.

**Comment by gaborcsardi** [comment]
So we would have `{.pkg.lst {packages}}` for a package list.

**Comment by gaborcsardi** [comment]
@hadley: So we would allow chaining inline formatters, and then `.lst` can work naturally, in itself: `{.lst {packages}}` or after another formatter: `{.file.lst {paths}}`. 

OTOH, I don't love the `{.file.lst {paths}}` syntax.

**Comment by hadley** [comment]
Maybe call it `.comma`? Maybe the package and file formatters should collapse by default?

**Comment by gaborcsardi** [comment]
Maybe all of them should collapse? In the context of cli, it does not make too much sense to vectorize here.

**Comment by gaborcsardi** [comment]
Alternatively I was also thinking just adding a `s`, like `.envvvars`, `.pkgs`, etc. None of them end with an `s` currently, so this might work, although it is somewhat magical.

**Comment by hadley** [comment]
Yeah, I think just collapse

**Comment by gaborcsardi** [comment]
@hadley I would vote for auto-collapsing, especially as this is what we have right now: 
```r
❯ pkg <- paste0("pkg", 1:5)
❯ cli_text("{.pkg {pkg}}")
pkg1pkg2pkg3pkg4pkg5
```

**Comment by gaborcsardi** [comment]
:) right, auto-collapsing it is then.

**Comment by gaborcsardi** [comment]
Unfortunately, this is surprisingly hard, because cli applies collapsing first (potentially in another process), and the theme only later, and we want this the other way...
