### ISSUE TITLE
printing as message during parallel processing

### ISSUE THREAD

**Issue by topepo** [r-lib/cli#93]
Do `cli` alerts use `message()`? I have s few test cases (with parallel processing) were the output from `message()` comes through but `cli_alert_info()` doesn't. Examples: 

macOS terminal: https://github.com/topepo/parallel-printing/blob/8a65f203c5c00eb11d67fc114962cfb191135cdc/macOS/terminal/doParallel_psock_future.Rout#L56

macOS IDE: https://github.com/topepo/parallel-printing/blob/8a65f203c5c00eb11d67fc114962cfb191135cdc/macOS/RStudio/doParallel_psock_future.Rout#L37

I looked through the `cli` sources but had a hard time finding where `app` and `type` were set.

**Comment by gaborcsardi** [comment]
I don't think it works with future.

**Comment by gaborcsardi** [comment]
Actually, I don't see why it would not work, if `message()` goes through.

**Comment by topepo** [comment]
I just ran on Win10 and had the same results.

**Comment by gaborcsardi** [comment]
I managed to track this down finally. It seems that future is trying to be smart about conditions and restarts, and it just calls any `muffle*` restart it can find, which is probably not a good idea: 
https://github.com/HenrikBengtsson/future/blob/cf27853bf94b592e73a50a9da9c2a069cd325824/R/signalConditions.R#L224

I'll fix this in cli in a minute.
